require('./local-test-env.cjs').localTestEnvironment();
require('ts-node/register'); require('tsconfig-paths/register');
const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('crypto'),bcrypt=require('bcrypt');
const {PrismaClient}=require('@prisma/client'),{ConfigService}=require('@nestjs/config'),{JwtService}=require('@nestjs/jwt');
const {AdminAccountsService}=require('../src/application/services/admin-accounts.service'),{AuthorizationService}=require('../src/domain/security/authorization.service');
const {AuthService}=require('../src/infrastructure/auth/auth.service'),{JwtStrategy}=require('../src/infrastructure/auth/jwt.strategy');
const {StaffService}=require('../src/application/services/staff.service'),{AttendanceService}=require('../src/application/services/attendance.service'),{PeriodExportService}=require('../src/application/services/period-export.service');
const db=new PrismaClient(),az=new AuthorizationService(),svc=new AdminAccountsService(db,az),jwt=new JwtStrategy(new ConfigService(),db),staff=new StaffService(db,az);
const auth=new AuthService(db,new JwtService({secret:process.env.JWT_SECRET}),{getFailedAttempts:async()=>0,incrementFailedAttempts:async()=>1,resetFailedAttempts:async()=>{},setRefreshToken:async()=>{}},new ConfigService());
const tag=randomUUID(),secret=()=>randomUUID()+'Az!9',password=secret(),nextPassword=secret();let companies=[],a,b,c,root,owner,manager;
const perms=['MANAGERS_VIEW','MANAGERS_CREATE','MANAGERS_EDIT','STAFF_VIEW','TIME_VIEW'];
async function user(role,company=companies[0]){return db.user.create({data:{companyId:company.id,role,email:randomUUID()+'@test.invalid',employeeNumber:randomUUID(),firstName:'Test',lastName:role,passwordHash:'not-login'}});}
const dto=(extra={})=>({firstName:'Beta',lastName:'Manager',email:randomUUID()+'@test.invalid',role:'MANAGER',companyId:companies[0].id,status:'ACTIVE',grants:[{propertyId:a.id,permissions:['STAFF_VIEW','TIME_VIEW']}],password,...extra});
const principal=id=>jwt.validate({sub:id});
async function editData(id,extra={}){const row=(await svc.list(root)).find(r=>r.id===id);return {firstName:row.firstName,lastName:row.lastName,role:row.role,companyId:row.companyId,status:row.status,grants:row.grants.map(g=>({propertyId:g.propertyId,permissions:g.permissions})),version:row.version,...extra};}
before(async()=>{assert.equal((await db.$queryRawUnsafe('SELECT current_database() AS name'))[0].name,'nexustaff_test');for(const n of ['A','B'])companies.push(await db.company.create({data:{name:tag+n,taxId:tag+n}}));async function property(company,n){return db.location.create({data:{companyId:company.id,name:n,locationCode:tag+n,address:'Test',timezone:'America/New_York'}});}a=await property(companies[0],'A');b=await property(companies[0],'B');c=await property(companies[1],'C');root=await user('SUPER_ADMIN');owner=await user('OWNER');});
after(async()=>{for(const company of companies){await db.user.deleteMany({where:{companyId:company.id}});await db.company.delete({where:{id:company.id}});}await db.$disconnect();});
test('SUPER_ADMIN creates multi-property manager with hashed credentials and administrative grants only',async()=>{manager=await svc.save(null,dto({grants:[{propertyId:a.id,permissions:perms},{propertyId:b.id,permissions:['TIME_VIEW']}]}),root);const row=await db.user.findUnique({where:{id:manager.id}});assert.equal(row.role,'MANAGER');assert.notEqual(row.passwordHash,password);assert.ok(await bcrypt.compare(password,row.passwordHash));assert.equal(await db.employeeAssignment.count({where:{userId:row.id}}),0);assert.equal(await db.userPropertyAccess.count({where:{userId:row.id}}),2);assert.equal(await db.userLocationAssignment.count({where:{userId:row.id}}),2);const safe=JSON.stringify(await svc.list(root));assert.ok(!safe.includes(password)&&!safe.includes(row.passwordHash));});
test('OWNER creates own company ADMIN but cannot create foreign or peer/platform accounts',async()=>{await svc.save(null,dto({role:'ADMIN'}),owner);for(const change of [{companyId:companies[1].id,grants:[{propertyId:c.id,permissions:[]}]},{role:'OWNER'},{role:'SUPER_ADMIN'}])await assert.rejects(svc.save(null,dto(change),owner));assert.ok((await svc.catalog(owner)).companies.every(x=>x.id===companies[0].id));});
for(const role of ['ADMIN','MANAGER','LOCATION_ADMIN','SUPERVISOR','WORKER'])test(role+' without delegation denied even with spoofed principal role',async()=>{const actor=await user(role);await assert.rejects(svc.catalog({...actor,role:'SUPER_ADMIN'}));await assert.rejects(svc.save(null,dto({role:'SUPERVISOR'}),actor));});
for(const role of ['ADMIN','MANAGER','LOCATION_ADMIN'])test(role+' explicit delegation remains branch/permission/rank constrained',async()=>{const actor=await user(role);await db.userPropertyAccess.create({data:{userId:actor.id,propertyId:a.id,permissions:perms}});await svc.save(null,dto({role:'SUPERVISOR',grants:[{propertyId:a.id,permissions:['STAFF_VIEW']}]}),actor);for(const change of [{role:'SUPER_ADMIN'},{role},{grants:[{propertyId:b.id,permissions:[]}]},{grants:[{propertyId:c.id,permissions:[]}]},{grants:[{propertyId:a.id,permissions:['VIEW_PAY_RATE']}]}])await assert.rejects(svc.save(null,dto(change),actor));await assert.rejects(svc.save(manager.id,await editData(manager.id),actor));});
test('password reset authenticates new password and rejects old; audit excludes credentials',async()=>{const row=await db.user.findUnique({where:{id:manager.id}});await auth.login({email:row.email,password});await svc.reset(row.id,nextPassword,row.updatedAt.toISOString(),owner);await assert.rejects(auth.login({email:row.email,password}));assert.equal((await auth.login({email:row.email,password:nextPassword})).user.id,row.id);const logs=await db.auditLog.findMany({where:{targetEntity:'User:'+row.id}});assert.ok(logs.some(x=>x.action==='ADMIN_PASSWORD_RESET'));assert.ok(!JSON.stringify(logs).includes(password)&&!JSON.stringify(logs).includes(nextPassword));});
test('updated scope rehydrates from DB and constrains Staff, Attendance, Reports and financial fields',async()=>{await svc.save(manager.id,await editData(manager.id,{grants:[{propertyId:a.id,permissions:['STAFF_VIEW','TIME_VIEW']}]}),root);const actor=await principal(manager.id);assert.deepEqual(actor.assignedLocationIds,[a.id]);assert.equal(az.hasPermission(actor,'VIEW_PAY_RATE',a.id,companies[0].id),false);assert.deepEqual(await staff.findAll([b.id],actor),[]);const rows=await staff.findAll(undefined,actor);assert.ok(rows.length>0);for(const row of rows)assert.equal(row.hourlyRate,undefined);const attendance=new AttendanceService(db,{},{}),exports=new PeriodExportService(db);await assert.rejects(attendance.getPunches({location_id:b.id},actor));await assert.rejects(exports.csv('detail',{period:'weekly',start_date:'2026-01-05',location_id:b.id},actor));assert.ok(await exports.csv('detail',{period:'weekly',start_date:'2026-01-05',location_id:a.id},actor));});
test('self/platform changes and legacy Staff admin mutations denied',async()=>{await assert.rejects(svc.save(root.id,{...dto(),password:undefined},root));await assert.rejects(svc.reset(root.id,nextPassword,root.updatedAt.toISOString(),root));await assert.rejects(staff.update(manager.id,{role:'SUPER_ADMIN'},root));await assert.rejects(staff.remove(root.id,root));await assert.rejects(staff.create({role:'ADMIN'},root));});
test('concurrent stale updates have one winner and inactive account rejects login and JWT',async()=>{const data=await editData(manager.id,{status:'TERMINATED'});const results=await Promise.allSettled([svc.save(manager.id,data,root),svc.save(manager.id,data,root)]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);const row=await db.user.findUnique({where:{id:manager.id}});await assert.rejects(auth.login({email:row.email,password:nextPassword}));await assert.rejects(principal(row.id));});
