require('ts-node/register');require('tsconfig-paths/register');
const {test}=require('node:test'),assert=require('node:assert/strict');
const {AdminAccountsController}=require('../src/adapters/controllers/admin-accounts.controller');
const {validateAdminPassword}=require('../src/application/services/admin-accounts.service');
const {ForbiddenException}=require('@nestjs/common');
test('password policy rejects weak and bcrypt-truncated inputs',()=>{for(const value of [undefined,'short','Password123456!!!!','a'.repeat(80)+'Az1!','Å'.repeat(40)+'azAZ1!'])assert.throws(()=>validateAdminPassword(value));assert.doesNotThrow(()=>validateAdminPassword('Fixture-Test-Az!987654'));});
test('controller sanitizes unexpected credential-bearing dependency failures without logging',async()=>{const marker='sensitive-test-marker',controller=new AdminAccountsController({save:async()=>{throw new Error(marker);}});const messages=[],original=console.error;console.error=(...args)=>messages.push(args);try{await assert.rejects(controller.create({password:marker},{user:{id:'u'}}),e=>e.getStatus()===503&&!JSON.stringify(e.getResponse()).includes(marker));assert.deepEqual(messages,[]);}finally{console.error=original;}});
test('controller preserves controlled authorization denial',async()=>{const controller=new AdminAccountsController({catalog:async()=>{throw new ForbiddenException('Denied');}});await assert.rejects(controller.catalog({user:{id:'u'}}),e=>e.getStatus()===403);});
test('global role guard allows company OWNER without legacy assignments and denies WORKER',()=>{const {RolesAndLocationsGuard}=require('../src/adapters/guards/roles-and-locations.guard'),{Reflector}=require('@nestjs/core');const guard=new RolesAndLocationsGuard(new Reflector());let user={role:'OWNER',assignedLocationIds:[]};const context={getHandler:()=>AdminAccountsController.prototype.catalog,getClass:()=>AdminAccountsController,switchToHttp:()=>({getRequest:()=>({user,headers:{},query:{}})})};assert.equal(guard.canActivate(context),true);user={role:'WORKER',assignedLocationIds:['a']};assert.throws(()=>guard.canActivate(context));});
