require('ts-node/register');require('tsconfig-paths/register');
const {test}=require('node:test'),assert=require('node:assert/strict'),bcrypt=require('bcrypt');
const {AuthService}=require('../src/infrastructure/auth/auth.service'),{RedisService}=require('../src/infrastructure/cache/redis.service');
async function fixture(fail){let count=0,reads=0,signs=0,ttl;const redis=new RedisService({get:()=>undefined});redis.client={get:async()=>{if(fail==='read')throw Error('private Redis address');return String(count);},eval:async(_s,_n,_k,t)=>{if(fail==='increment')throw Error('private Redis address');ttl=t;return ++count;},del:async()=>{if(fail==='reset')throw Error('private Redis address');count=0;},set:async()=>{}};const user={id:'u',email:'synthetic@test.invalid',role:'OWNER',companyId:'c',status:'ACTIVE',passwordHash:await bcrypt.hash('Synthetic-Test!804927',4),assignments:[],employeeAssignments:[],propertyAccess:[]};const db={user:{findUnique:async()=>{reads++;return user;}}};const svc=new AuthService(db,{sign:()=>{signs++;return 'synthetic-token';}},redis,{get:()=> 'synthetic-local-test-signing-secret'});return{svc,redis,db,user,state:()=>({count,reads,signs,ttl}),setCount:n=>count=n};}
const login=f=>f.svc.login({email:'synthetic@test.invalid',password:'Synthetic-Test!804927'});
test('available Redis permits bcrypt login and clears counter before issuance',async()=>{const f=await fixture();f.setCount(2);assert.ok((await login(f)).tokens);assert.deepEqual(f.state(),{count:0,reads:1,signs:2,ttl:undefined});});
test('wrong password counts atomically with existing 900 second duration; fifth failure locks',async()=>{const f=await fixture();for(let i=1;i<=5;i++){await assert.rejects(f.svc.login({email:f.user.email,password:'wrong'}),e=>e.getStatus()===401);assert.equal(f.state().count,i);assert.equal(f.state().ttl,900);}const reads=f.state().reads;await assert.rejects(login(f),e=>e.getStatus()===401);assert.equal(f.state().reads,reads);assert.equal(f.state().signs,0);});
for(const phase of ['read','increment','reset'])test('Redis '+phase+' outage produces safe 503 with no token issuance',async()=>{const f=await fixture(phase);await assert.rejects(phase==='increment'?f.svc.login({email:f.user.email,password:'wrong'}):login(f),e=>e.getStatus()===503&&e.message==='Login temporarily unavailable. Please try later.');assert.equal(f.state().signs,0);if(phase==='read')assert.equal(f.state().reads,0);});
test('unknown account increment also fails closed',async()=>{const f=await fixture('increment');f.db.user.findUnique=async()=>null;await assert.rejects(login(f),e=>e.getStatus()===503);assert.equal(f.state().signs,0);});
test('malformed Redis counter is not interpreted as zero',async()=>{const f=await fixture();f.redis.client.get=async()=> 'not-a-counter';await assert.rejects(login(f),e=>e.getStatus()===503);assert.equal(f.state().reads,0);});
