require('./local-test-env.cjs').localTestEnvironment();require('ts-node/register');require('tsconfig-paths/register');
const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),crypto=require('crypto'),{PrismaClient}=require('@prisma/client');
const {AuthorizationService}=require('../src/domain/security/authorization.service'),{StaffService}=require('../src/application/services/staff.service'),{LocationService}=require('../src/application/services/location.service');
const db=new PrismaClient(),authz=new AuthorizationService();let company,worker,requester,branch,correction;
before(async()=>{assert.equal((await db.$queryRawUnsafe('SELECT current_database() AS name'))[0].name,'nexustaff_test');const tag=crypto.randomUUID();company=await db.company.create({data:{name:'AUDIT DISPOSABLE '+tag,taxId:tag}});const base={companyId:company.id,firstName:'Synthetic',lastName:'Audit',passwordHash:'not-a-login'};requester=await db.user.create({data:{...base,employeeNumber:'ADM-'+tag,email:tag+'@audit.invalid',role:'SUPER_ADMIN'}});worker=await db.user.create({data:{...base,employeeNumber:'EMP-'+tag,email:'worker-'+tag+'@audit.invalid',role:'WORKER'}});branch=await db.location.create({data:{companyId:company.id,name:'Audit test',locationCode:tag,address:'Test',timezone:'UTC'}});correction=await db.timeCorrectionRequest.create({data:{userId:worker.id,propertyId:branch.id,requestedById:requester.id,requestedTimestamp:new Date(),correctionType:'MISSED_CLOCK_OUT',reason:'Disposable FK retention test'}});});
after(async()=>{if(company){await db.timeCorrectionRequest.deleteMany({where:{property:{companyId:company.id}}});await db.user.deleteMany({where:{companyId:company.id}});await db.company.delete({where:{id:company.id}});}await db.$disconnect();});
test('actual PostgreSQL FKs use RESTRICT for Staff, Branch and requester',async()=>{const rows=await db.$queryRawUnsafe("SELECT conname, confdeltype FROM pg_constraint WHERE conrelid='time_correction_requests'::regclass AND conname IN ('time_correction_requests_user_id_fkey','time_correction_requests_property_id_fkey','time_correction_requests_requested_by_id_fkey')");assert.equal(rows.length,3);assert.ok(rows.every(r=>r.confdeltype==='r'));});
for(const target of ['worker','branch','requester'])test('hard deletion of referenced '+target+' is rejected and history survives',async()=>{const original=await db.timeCorrectionRequest.findUnique({where:{id:correction.id}});await assert.rejects(target==='branch'?db.location.delete({where:{id:branch.id}}):db.user.delete({where:{id:(target==='worker'?worker:requester).id}}),e=>e.code==='P2003');assert.deepEqual(await db.timeCorrectionRequest.findUnique({where:{id:correction.id}}),original);});
test('normal Staff soft termination and Branch update preserve correction history',async()=>{await new StaffService(db,authz).update(worker.id,{status:'TERMINATED'},requester);assert.equal((await db.user.findUnique({where:{id:worker.id}})).status,'TERMINATED');await new LocationService(db,authz).update(branch.id,{name:'Audit updated'},requester);assert.equal((await db.location.findUnique({where:{id:branch.id}})).name,'Audit updated');assert.ok(await db.timeCorrectionRequest.findUnique({where:{id:correction.id}}));});
