require('ts-node/register');require('tsconfig-paths/register');
const {test}=require('node:test'),assert=require('node:assert/strict'),bcrypt=require('bcrypt'),crypto=require('crypto');
process.env.PIN_LOOKUP_KEY=crypto.randomBytes(32).toString('hex');process.env.PIN_ENCRYPTION_KEY=crypto.randomBytes(32).toString('hex');
const {AttendanceService}=require('../src/application/services/attendance.service');
const {StaffService}=require('../src/application/services/staff.service');
const {AuthorizationService}=require('../src/domain/security/authorization.service');
const {pinLookupDigest,pinLookupKeyFingerprint,assertNoPinConflict}=require('../src/infrastructure/security/pin-lookup');
const {backfillPinLookup}=require('../src/infrastructure/security/pin-lookup-backfill');
const {encryptPin}=require('../src/infrastructure/security/pin-encryption.util');
const {KioskPinDto,KioskStatusDto}=require('../src/adapters/dtos/attendance.dtos');
const {ValidationPipe}=require('@nestjs/common');
const property='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',dto={pin_code:'908172',property_id:property};
async function fixture(){
 const hash=await bcrypt.hash(dto.pin_code,4),assignment={propertyId:property,active:true,effectiveFrom:new Date(0),effectiveUntil:null,departmentId:'d',positionId:'p',department:{id:'d',name:'Team'},position:{id:'p',title:'Role'}};
 const rows=[{id:'u',companyId:'c',status:'ACTIVE',employeeNumber:'EMP-T',firstName:'Test',lastName:'Staff',pinCodeHash:hash,pinLookupDigest:pinLookupDigest(dto.pin_code),employeeAssignments:[assignment],assignments:[]}];
 let query,down=false,key=pinLookupKeyFingerprint(),collision=false;const counters=new Map(),writes=[],audits=[];
 const eligible=u=>u.companyId==='c'&&u.status==='ACTIVE'&&u.employeeAssignments.some(a=>a.propertyId===property&&a.active&&a.effectiveFrom<=new Date()&&(!a.effectiveUntil||a.effectiveUntil>=new Date()));
 const db={pinLookupConfig:{findUnique:async()=>key?{keyFingerprint:key}:null},location:{findUnique:async()=>({id:property,companyId:'c',name:'Branch',timezone:'UTC'})},user:{findMany:async q=>{query=q;return rows.filter(u=>eligible(u)&&u.pinLookupDigest===q.where.pinLookupDigest).slice(0,q.take);},findFirst:async()=>rows.find(u=>eligible(u)&&u.pinCodeHash&&!u.pinLookupDigest)||null,findUnique:async({where})=>rows.find(u=>where.id?u.id===where.id:u.employeeNumber===where.employeeNumber),update:async({where,data})=>{writes.push(data);Object.assign(rows.find(u=>u.id===where.id),data);return rows.find(u=>u.id===where.id);}},employeeAssignment:{findMany:async()=>rows[0].employeeAssignments,findFirst:async()=>collision?{id:'conflict'}:null},auditLog:{create:async data=>audits.push(data)},$executeRawUnsafe:async sql=>{assert.match(sql,/pg_advisory_xact_lock/);}};
 db.$transaction=async fn=>{const snapshot=structuredClone(rows),count=audits.length;try{return await fn(db);}catch(e){rows.splice(0,rows.length,...snapshot);audits.length=count;throw e;}};
 const redis={incrementFailedAttempts:async(k,ttl,strict)=>{assert.equal(strict,true);if(down)throw Error('private');const n=(counters.get(k)||0)+1;counters.set(k,n);return n;},getFailedAttempts:async(k,strict)=>{assert.equal(strict,true);if(down)throw Error('private');return counters.get(k)||0;},resetFailedAttempts:async k=>{if(down)throw Error('private');counters.delete(k);}};
 return {db,rows,writes,audits,counters,svc:new AttendanceService(db,redis,{getEmployeeShiftState:async()=>({currentStatus:'OFF_SHIFT',allowedActions:['CLOCK_IN']})}),query:()=>query,down:()=>down=true,badKey:()=>key='wrong',conflict:()=>collision=true};
}
const identify=f=>f.svc.identifyKioskPin(dto,'127.0.0.1');
test('indexed lookup across 1500 staff performs one bcrypt comparison, returns sanitized canonical context',async()=>{const f=await fixture();for(let i=0;i<1500;i++)f.rows.push({...f.rows[0],id:'other'+i,employeeNumber:'EMP-'+i,pinLookupDigest:pinLookupDigest(String(i).padStart(6,'0'))});const original=bcrypt.compare;let comparisons=0;bcrypt.compare=async(...args)=>{comparisons++;return original(...args);};try{const result=await identify(f);assert.equal(result.employee.employeeNumber,'EMP-T');assert.equal(comparisons,1);assert.doesNotMatch(JSON.stringify(result),/pinCode|pinLookup|908172/);}finally{bcrypt.compare=original;}const q=f.query();assert.equal(q.where.pinLookupDigest,pinLookupDigest(dto.pin_code));assert.equal(q.where.companyId,'c');assert.equal(q.where.employeeAssignments.some.propertyId,property);assert.equal(q.take,2);assert.deepEqual(q.select,{employeeNumber:true});});
test('duplicate eligible PIN is never resolved arbitrarily',async()=>{const f=await fixture();f.rows.push({...f.rows[0],id:'other',employeeNumber:'EMP-OTHER'});await assert.rejects(identify(f),e=>e.getStatus()===401);});
for(const scenario of ['foreign company','foreign branch','future','expired','inactive assignment','terminated'])test('indexed lookup denies '+scenario,async()=>{const f=await fixture(),u=f.rows[0],a=u.employeeAssignments[0];if(scenario==='foreign company')u.companyId='foreign';if(scenario==='foreign branch')a.propertyId='foreign';if(scenario==='future')a.effectiveFrom=new Date(Date.now()+86400000);if(scenario==='expired')a.effectiveUntil=new Date(0);if(scenario==='inactive assignment')a.active=false;if(scenario==='terminated')u.status='TERMINATED';await assert.rejects(identify(f),e=>e.getStatus()===401);});
test('index is not credential authority: mismatched canonical bcrypt still rejects',async()=>{const f=await fixture();f.rows[0].pinCodeHash=await bcrypt.hash('111111',4);await assert.rejects(identify(f),e=>e.getStatus()===401);});
test('legacy account lockout still applies',async()=>{const f=await fixture();f.counters.set('kiosk_pin:EMP-T',5);await assert.rejects(identify(f),e=>e.getStatus()===401);});
test('unindexed eligible legacy user blocks branch to prevent mistaken identity',async()=>{const f=await fixture();f.rows.push({...f.rows[0],id:'legacy',pinLookupDigest:null});await assert.rejects(identify(f),e=>e.getStatus()===503);assert.equal(f.query(),undefined);});
test('key drift fails closed without scanning hashes',async()=>{const f=await fixture();f.badKey();await assert.rejects(identify(f),e=>e.getStatus()===503);});
test('five wrong PINs do not disable unrelated staff',async()=>{const f=await fixture();for(let i=0;i<5;i++)await assert.rejects(f.svc.identifyKioskPin({...dto,pin_code:'999999'},'127.0.0.1'));assert.equal((await identify(f)).employee.employeeNumber,'EMP-T');await assert.rejects(f.svc.identifyKioskPin({...dto,pin_code:'999999'},'127.0.0.2'),e=>e.getStatus()===401);});
test('Redis unavailable blocks before lookup; missing client context also fails',async()=>{const f=await fixture();f.down();await assert.rejects(identify(f),e=>e.getStatus()===503);assert.equal(f.query(),undefined);await assert.rejects(f.svc.identifyKioskPin(dto,''),e=>e.getStatus()===503);});
test('per-client rate budget does not lock another client or entire branch',async()=>{const f=await fixture();for(let i=0;i<60;i++)await assert.rejects(f.svc.identifyKioskPin({...dto,pin_code:'999999'},'client-a'));await assert.rejects(f.svc.identifyKioskPin(dto,'client-a'),e=>e.getStatus()===401);assert.equal((await f.svc.identifyKioskPin(dto,'client-b')).employee.employeeNumber,'EMP-T');});
test('PIN reset atomically synchronizes index/hash/encrypted record and safe audit; old lookup stops',async()=>{const f=await fixture();const svc=new StaffService(f.db,new AuthorizationService());await svc.resetPin('u','123987',{id:'admin',role:'SUPER_ADMIN'});assert.equal(f.rows[0].pinLookupDigest,pinLookupDigest('123987'));assert.ok(await bcrypt.compare('123987',f.rows[0].pinCodeHash));assert.equal(f.audits.length,1);assert.doesNotMatch(JSON.stringify(f.audits),/123987|pinLookupDigest/);await assert.rejects(identify(f));assert.equal((await f.svc.identifyKioskPin({...dto,pin_code:'123987'},'client')).employee.employeeNumber,'EMP-T');});
test('duplicate PIN reset rolls back credential tuple',async()=>{const f=await fixture();const original={...f.rows[0]};f.conflict();await assert.rejects(new StaffService(f.db,new AuthorizationService()).resetPin('u','123987',{id:'admin',role:'SUPER_ADMIN'}),e=>e.getStatus()===409);assert.equal(f.rows[0].pinLookupDigest,original.pinLookupDigest);assert.equal(f.rows[0].pinCodeHash,original.pinCodeHash);assert.equal(f.audits.length,0);});
test('overlap check includes all future multi-property assignments',async()=>{const f=await fixture();let queries=[];f.db.employeeAssignment.findFirst=async q=>{queries.push(q);return null;};f.rows[0].employeeAssignments.push({...f.rows[0].employeeAssignments[0],propertyId:'second',effectiveFrom:new Date('2030-01-01'),effectiveUntil:new Date('2030-02-01')});await assertNoPinConflict(f.db,'u');assert.equal(queries.length,2);assert.equal(queries[1].where.propertyId,'second');assert.equal(+queries[1].where.effectiveFrom.lte,+new Date('2030-02-01'));});
test('strict PIN DTO preserves original employee-number contract on status/clock',async()=>{const pipe=new ValidationPipe({transform:true,whitelist:true,forbidNonWhitelisted:true});await pipe.transform(dto,{type:'body',metatype:KioskPinDto});for(const invalid of [{pin_code:'908172'},{...dto,pin_code:'123'},{...dto,employee_number:'injected'}])await assert.rejects(pipe.transform(invalid,{type:'body',metatype:KioskPinDto}));await assert.rejects(pipe.transform(dto,{type:'body',metatype:KioskStatusDto}));});
test('backfill dry run changes nothing; apply only digests; bcrypt-only users require authorized enrollment',async()=>{const f=await fixture();f.rows[0].pinCodeEncrypted=encryptPin(dto.pin_code);f.rows.push({...f.rows[0],id:'legacy',pinCodeEncrypted:null,employeeAssignments:[]});f.db.user.findMany=async()=>f.rows;let configWrites=0;f.db.pinLookupConfig.upsert=async()=>configWrites++;const dry=await backfillPinLookup(f.db);assert.equal(dry.needsAuthorizedReset,1);assert.equal(f.writes.length,0);await backfillPinLookup(f.db,true);assert.equal(f.writes.length,2);assert.deepEqual(Object.keys(f.writes[0]),['pinLookupDigest']);assert.equal(configWrites,1);assert.equal(f.rows[1].pinLookupDigest,null);});
test('backfill refuses overlapping duplicate enrollment without writes or automatic PIN reset',async()=>{const f=await fixture();f.rows[0].pinCodeEncrypted=encryptPin(dto.pin_code);f.rows.push({...f.rows[0],id:'duplicate'});f.db.user.findMany=async()=>f.rows;const report=await backfillPinLookup(f.db);assert.equal(report.overlappingConflicts,1);await assert.rejects(backfillPinLookup(f.db,true),e=>e.getStatus()===409);assert.equal(f.writes.length,0);});

test('backfill with an unverifiable encrypted record fails atomically instead of clearing existing enrollment',async()=>{const f=await fixture();f.rows[0].pinCodeEncrypted='invalid-record';f.db.user.findMany=async()=>f.rows;const old=f.rows[0].pinLookupDigest;const report=await backfillPinLookup(f.db);assert.equal(report.invalidEncryptedRecords,1);assert.equal(report.needsAuthorizedReset,0);await assert.rejects(backfillPinLookup(f.db,true),e=>e.getStatus()===409);assert.equal(f.writes.length,0);assert.equal(f.rows[0].pinLookupDigest,old);});
test('lookup key requires independent 32-byte secret without defaults',()=>{const {pinLookupKey}=require('../src/infrastructure/security/pin-lookup');for(const env of [{},{PIN_LOOKUP_KEY:'short'},{PIN_LOOKUP_KEY:'x'.repeat(64)},{PIN_LOOKUP_KEY:'a'.repeat(64),PIN_ENCRYPTION_KEY:'a'.repeat(64)},{PIN_LOOKUP_KEY:'a'.repeat(64),JWT_SECRET:'a'.repeat(64)}])assert.throws(()=>pinLookupKey(env));assert.equal(pinLookupKey({PIN_LOOKUP_KEY:'a'.repeat(64)}).length,32);});

test('adding an eligible property assignment locks PIN index before employee row and rolls back conflicts',async()=>{const f=await fixture();const {OnboardingService}=require('../src/application/services/onboarding.service');const events=[];f.db.$executeRawUnsafe=async()=>events.push('index');f.db.$queryRaw=async()=>events.push('row');f.rows[0].role='WORKER';f.db.department={findUnique:async()=>({id:'d',locationId:property})};f.db.position={findUnique:async()=>({id:'p',locationId:property,departmentId:'d',active:true})};f.db.userLocationAssignment={upsert:async()=>{}};let overlapRead=0;f.db.employeeAssignment.findMany=async()=>overlapRead++===0?[]:f.rows[0].employeeAssignments;f.db.employeeAssignment.create=async()=>({id:'new-assignment'});f.conflict();await assert.rejects(new OnboardingService(f.db,new AuthorizationService()).add('u',{propertyId:property,departmentId:'d',positionId:'p',effectiveFrom:'2030-01-01'}, {id:'admin',role:'SUPER_ADMIN'}),e=>e.getStatus()===409);assert.deepEqual(events,['index','row']);assert.equal(f.audits.length,0);});
