require('ts-node/register');require('tsconfig-paths/register');
const {test}=require('node:test'),assert=require('node:assert/strict');
const {PeriodExportService,exportPeriod,csvCell}=require('../src/application/services/period-export.service');
const {ReportsController}=require('../src/adapters/controllers/reports.controller');
const {Reflector}=require('@nestjs/core');
const {PermissionsGuard}=require('../src/adapters/guards/permissions.guard');
const {AuthorizationService}=require('../src/domain/security/authorization.service');
const query={period:'custom',start_date:'2026-01-01',end_date:'2026-01-14'};
const admin={id:'admin',role:'SUPER_ADMIN'};
function fixture(count=1){
 const properties=[{id:'a',companyId:'one'},{id:'b',companyId:'one'},{id:'foreign',companyId:'two'}];
 const shifts=Array.from({length:count},(_,i)=>({id:String(i).padStart(6,'0'),userId:'u',locationId:'a',clockInTimestamp:new Date('2026-01-02T08:00Z'),clockOutTimestamp:new Date('2026-01-02T16:00Z'),effectiveClockIn:null,effectiveClockOut:null,regularMinutes:420,overtimeMinutes:0,status:'COMPLETED',user:{id:'u',firstName:'Actual',lastName:'Staff',employeeNumber:'EMP-1'},location:{id:'a',name:'Branch A',locationCode:'A',timezone:'UTC',company:{id:'one',name:'Company One'}},department:{name:'Operations'},position:{title:'Staff'},logs:[{id:'l'+i,punchType:'LUNCH_START',timestamp:new Date('2026-01-02T12:00Z'),effectiveTimestamp:null,corrections:[]},{id:'e'+i,punchType:'LUNCH_END',timestamp:new Date('2026-01-02T13:00Z'),effectiveTimestamp:null,corrections:[]}],timeCorrections:[]}));
 const calls=[],sheets=[],orphans=[];let options;
 const db={location:{findUnique:async({where})=>properties.find(p=>p.id===where.id),findMany:async({where})=>properties.filter(p=>(!where.companyId||p.companyId===where.companyId)&&(!where.id||where.id.in.includes(p.id)))},attendanceLog:{findMany:async()=>orphans},timesheet:{findMany:async()=>sheets},workShift:{findMany:async args=>{calls.push(args);return shifts.filter(s=>args.where.locationId.in.includes(s.locationId)&&(!args.where.location||s.location.company.id===args.where.location.companyId)&&(!args.cursor||s.id>args.cursor.id)).slice(0,args.take);}},$transaction:async(fn,opt)=>{options=opt;return fn(db);}};
 return{db,shifts,calls,sheets,orphans,service:new PeriodExportService(db),options:()=>options};
}
test('detail exports 1105 complete shifts (>200) over three pages, no money or credential selections',async()=>{const f=fixture(1105),csv=(await f.service.csv('detail',query,admin)).toString();assert.equal(csv.split('\r\n').length,1106);assert.equal(f.calls.length,4);assert.equal(f.options().isolationLevel,'RepeatableRead');assert.doesNotMatch(JSON.stringify(f.calls),/payRate|billRate|password|pinLookup|pinCode|markup/);assert.equal(f.calls[1].cursor.id,'000499');});
test('summary counts shifts once despite many attendance events and deduplicates correction IDs',async()=>{const f=fixture(3);f.shifts[0].timeCorrections=[{id:'c',status:'APPROVED'}];f.shifts[0].logs[0].corrections=[{id:'c',status:'APPROVED'}];f.shifts[2].status='OPEN';f.shifts[2].clockOutTimestamp=null;const csv=(await f.service.csv('summary',query,admin)).toString();assert.equal(csv.split('\r\n').length,2);assert.match(csv,/"840","14.0000","1","1"/);assert.match(csv,/PARTIAL_COMPLETED_SHIFTS_ONLY/);});
test('approved correction exports effective values without inventing raw clock-out',async()=>{const f=fixture();const s=f.shifts[0];s.clockOutTimestamp=null;s.effectiveClockOut=new Date('2026-01-02T17:00Z');s.regularMinutes=480;s.timeCorrections=[{id:'c',status:'APPROVED'}];const csv=(await f.service.csv('detail',query,admin)).toString();assert.match(csv,/17:00:00.000Z/);assert.match(csv,/"480","8.0000"/);assert.ok(csv.endsWith('"2026-01-02T08:00:00.000Z",""'));});
test('overnight shift belongs to effective branch-local start day, including DST boundary',async()=>{const f=fixture(2);f.shifts[0].clockInTimestamp=new Date('2026-03-09T02:00Z');f.shifts[0].location.timezone='America/New_York';f.shifts[1].clockInTimestamp=new Date('2026-03-09T05:00Z');f.shifts[1].location={...f.shifts[0].location};const csv=(await f.service.csv('detail',{period:'custom',start_date:'2026-03-08',end_date:'2026-03-08'},admin)).toString();assert.equal(csv.split('\r\n').length,2);assert.match(csv,/"2026-03-08"/);});
for(const role of ['LOCATION_ADMIN','SUPERVISOR','ADMIN','MANAGER'])test(role+' exports only explicitly authorized company properties',async()=>{const f=fixture(3);f.shifts[1].locationId='b';f.shifts[2].locationId='foreign';f.shifts[2].location={...f.shifts[2].location,company:{id:'two',name:'Foreign'}};const actor={id:'actor',role,companyId:'one',assignedLocationIds:['a','foreign'],permissions:['TIME_VIEW']};const csv=(await f.service.csv('detail',query,actor)).toString();assert.equal(csv.split('\r\n').length,2);assert.deepEqual(f.calls[0].where.locationId.in,['a']);await assert.rejects(f.service.csv('detail',{...query,location_id:'foreign'},actor),e=>e.getStatus()===403);});
test('OWNER gets own-company aggregate; SUPER_ADMIN can select one or all companies',async()=>{const f=fixture(3);f.shifts[1].locationId='b';f.shifts[2].locationId='foreign';f.shifts[2].location={...f.shifts[2].location,company:{id:'two',name:'Foreign'}};assert.equal((await f.service.csv('detail',query,{id:'o',role:'OWNER',companyId:'one'})).toString().split('\r\n').length,3);assert.equal((await f.service.csv('detail',query,admin)).toString().split('\r\n').length,4);assert.equal((await f.service.csv('detail',{...query,location_id:'a'},admin)).toString().split('\r\n').length,2);});
test('missing TIME_VIEW, unresolved company and conflicting scopes rejected before data reads',async()=>{const f=fixture();for(const actor of [{id:'s',role:'SUPERVISOR',companyId:'one',assignedLocationIds:['a']},{id:'s',role:'SUPERVISOR',permissions:['TIME_VIEW']}])await assert.rejects(f.service.csv('detail',query,actor),e=>e.getStatus()===403);await assert.rejects(f.service.csv('detail',{...query,location_id:'a'},admin,{'x-property-id':'b'}),e=>e.getStatus()===400);assert.equal(f.calls.length,0);});
test('weekly and biweekly are inclusive 7/14 calendar days; invalid and excessive ranges rejected',()=>{assert.equal(exportPeriod({period:'weekly',start_date:'2026-12-28'}).end,'2027-01-03');assert.equal(exportPeriod({period:'biweekly',start_date:'2026-12-28'}).end,'2027-01-10');for(const q of [{...query,start_date:'2026-02-30'},{...query,start_date:'2026-01-15'},{...query,end_date:'2028-01-01'},{period:'weekly',start_date:'2026-01-01',end_date:'2026-01-04'}])assert.throws(()=>exportPeriod(q));});
test('existing approval status/actor consumed only from matching timesheet; missing status stays unavailable',async()=>{const f=fixture();f.sheets.push({userId:'u',locationId:'a',period:{locationId:'a',startDate:new Date('2026-01-01'),endDate:new Date('2026-01-15')},status:'APPROVED',approvalHistory:[{newStatus:'APPROVED',actor:{firstName:'Actual',lastName:'Reviewer'}}]});assert.match((await f.service.csv('detail',query,admin)).toString(),/"APPROVED","Actual Reviewer"/);f.sheets.length=0;assert.match((await f.service.csv('detail',query,admin)).toString(),/NOT_AVAILABLE/);});
test('orphan attendance stops export rather than silently losing events',async()=>{const f=fixture();f.orphans.push({id:'orphan',timestamp:new Date('2026-01-02'),location:{timezone:'UTC'}});await assert.rejects(f.service.csv('detail',query,admin),e=>e.getStatus()===409);assert.equal(f.calls.length,0);});
test('CSV protects formulas including leading whitespace, quotes and commas',()=>{assert.equal(csvCell(' =SUM(1,2)'), '"\' =SUM(1,2)"');assert.equal(csvCell('A"B,C'),'"A""B,C"');assert.equal(csvCell(0),'"0"');});
test('actual export controller emits private attachment and sanitizes internal failure',async()=>{const f=fixture();const controller=new ReportsController({},f.service);const response={set(h){this.headers=h;},send(b){this.body=b;return b;}};await controller.detail(query,{user:admin,headers:{}},response);assert.equal(response.headers['Cache-Control'],'no-store');assert.equal(response.headers['Content-Type'],'text/csv; charset=utf-8');assert.ok(Buffer.isBuffer(response.body));f.service.csv=async()=>{throw Error('private SQL password');};await assert.rejects(controller.summary(query,{user:admin},response),e=>e.getStatus()===503&&!e.message.includes('private'));});
test('export routes retain property-scoped TIME_VIEW guard metadata',async()=>{const f=fixture();const guard=new PermissionsGuard(new Reflector(),new AuthorizationService(),f.db);const request={user:{id:'a',role:'SUPERVISOR',companyId:'one',assignedLocationIds:['a'],permissions:['TIME_VIEW']},query:{location_id:'a'},headers:{}};const context={getHandler:()=>ReportsController.prototype.detail,getClass:()=>ReportsController,switchToHttp:()=>({getRequest:()=>request})};assert.equal(await guard.canActivate(context),true);request.query.location_id='foreign';await assert.rejects(guard.canActivate(context),e=>e.getStatus()===403);});
