require('ts-node/register');require('tsconfig-paths/register');
const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('crypto');
const {Prisma}=require('@prisma/client');
const {OnboardingService}=require('../src/application/services/onboarding.service');
const {AuthorizationService}=require('../src/domain/security/authorization.service');
process.env.PIN_ENCRYPTION_KEY=crypto.randomBytes(32).toString('hex');
const dto={firstName:'Test',lastName:'Staff',employeeNumber:'EMP-TEST',pinCode:'654321',propertyId:'p',departmentId:'d',positionId:'pos',effectiveFrom:'2026-01-01T00:00:00Z'};
function fixture(error){let assignments=0;const tx={location:{findUnique:async()=>({id:'p',companyId:'c'})},department:{findUnique:async()=>({id:'d',locationId:'p'})},position:{findUnique:async()=>({id:'pos',active:true,locationId:'p',departmentId:'d',code:'POS'})},user:{create:async()=>{if(error)throw error;return{id:'u'};}},employeeAssignment:{findMany:async()=>[],create:async()=>{assignments++;return{id:'a'};}},userLocationAssignment:{upsert:async()=>({})},auditLog:{create:async()=>({})}};return{svc:new OnboardingService({$transaction:fn=>fn(tx)},new AuthorizationService()),count:()=>assignments};}
for(const [field,message] of [['email','A staff member with this email already exists.'],['employee_number','A staff member with this staff number already exists.'],['employeeNumber','A staff member with this staff number already exists.'],['private_constraint','A staff member with these details already exists.']])test(`P2002 ${field} is a safe 409 before assignment creation`,async()=>{const error=new Prisma.PrismaClientKnownRequestError('Prisma SQL internal /app/private',{code:'P2002',clientVersion:'5',meta:{target:[field]}});const f=fixture(error);await assert.rejects(f.svc.create(dto,{id:'a',role:'SUPER_ADMIN',companyId:'c'}),e=>{assert.equal(e.getStatus(),409);assert.equal(e.getResponse().message,message);assert.doesNotMatch(JSON.stringify(e.getResponse()),/Prisma|SQL|constraint|\/app/);return true;});assert.equal(f.count(),0);});
test('valid onboarding continues to create the assignment',async()=>{const f=fixture();assert.deepEqual(await f.svc.create(dto,{id:'a',role:'SUPER_ADMIN',companyId:'c'}),{id:'u'});assert.equal(f.count(),1);});
test('other failures are not misclassified as duplicate identity',async()=>{const error=new Error('unexpected');const f=fixture(error);await assert.rejects(f.svc.create(dto,{id:'a',role:'SUPER_ADMIN',companyId:'c'}),e=>e===error);});
