require('ts-node/register'); require('tsconfig-paths/register');
const {test}=require('node:test'), assert=require('node:assert/strict');
const {LocationService}=require('../src/application/services/location.service');
const {AuthorizationService}=require('../src/domain/security/authorization.service');
const actor={id:'admin',role:'SUPER_ADMIN',companyId:'company'};
const input={name:'Branch',code:'LOC-TEST',address:'Test address',timezone:'America/Merida'};
function fixture(){const writes=[]; const db={location:{create:async q=>{writes.push(q.data);return q.data;},findUnique:async()=>({...input,id:'property',companyId:'company'}),update:async q=>{writes.push(q.data);return q.data;}}};return {svc:new LocationService(db,new AuthorizationService()),writes};}
test('company-bound SUPER_ADMIN creates with canonical timezone and omitted companyId',async()=>{const {svc,writes}=fixture();await svc.create(input,actor);assert.equal(writes[0].companyId,'company');assert.equal(writes[0].timezone,'America/Merida');assert.equal(writes[0].operationalConfig.create.weekStartDay,'MONDAY');});
test('invalid city is rejected before persistence',async()=>{const {svc,writes}=fixture();await assert.rejects(svc.create({...input,timezone:'Merida'},actor),e=>e.getStatus()===400&&e.message==='A valid IANA timezone is required.');assert.equal(writes.length,0);});
test('create trims edges but preserves meaningful internal whitespace',async()=>{const {svc,writes}=fixture();await svc.create({...input,name:'  Branch  One  ',code:' LOC-TEST ',address:' Test  address ',timezone:' America/Merida \t'},actor);assert.equal(writes[0].name,'Branch  One');assert.equal(writes[0].address,'Test  address');assert.equal(writes[0].locationCode,'LOC-TEST');assert.equal(writes[0].timezone,'America/Merida');});
test('update normalizes timezone, name and address',async()=>{const {svc,writes}=fixture();await svc.update('property',{name:' Edited ',address:' Address ',timezone:' America/Merida '},actor);assert.equal(writes[0].timezone,'America/Merida');assert.equal(writes[0].name,'Edited');assert.equal(writes[0].address,'Address');});
test('blank and non-string timezone remain rejected',async()=>{for(const timezone of ['', '  ',null,123,{}]){const {svc,writes}=fixture();await assert.rejects(svc.create({...input,timezone},actor),/valid IANA timezone/);assert.equal(writes.length,0);}});
test('global SUPER_ADMIN still needs explicit company',async()=>{const {svc,writes}=fixture();await assert.rejects(svc.create(input,{...actor,companyId:null}),/explicit company/);assert.equal(writes.length,0);await svc.create({...input,companyId:'explicit'},{...actor,companyId:null});assert.equal(writes[0].companyId,'explicit');});
test('non-super actor cannot override company via payload',async()=>{const {svc,writes}=fixture();await assert.rejects(svc.create({...input,companyId:'foreign'},{...actor,role:'OWNER'}),e=>e.getStatus()===403);assert.equal(writes.length,0);});
test('blank required text is rejected with a controlled message',async()=>{for(const field of ['name','address']){const {svc,writes}=fixture();await assert.rejects(svc.create({...input,[field]:' '},actor),e=>e.getStatus()===400&&e.message===`Property ${field} is required.`);assert.equal(writes.length,0);}});
