require('./local-test-env.cjs').localTestEnvironment();require('ts-node/register');require('tsconfig-paths/register');
const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),crypto=require('crypto'),bcrypt=require('bcrypt');
const {PrismaClient}=require('@prisma/client'),{ConfigService}=require('@nestjs/config'),{Reflector}=require('@nestjs/core');
const {AuthorizationService}=require('../src/domain/security/authorization.service'),{OnboardingService}=require('../src/application/services/onboarding.service'),{StaffService}=require('../src/application/services/staff.service');
const {AttendanceService}=require('../src/application/services/attendance.service'),{WorkShiftService}=require('../src/application/services/work-shift.service'),{RedisService}=require('../src/infrastructure/cache/redis.service');
const {PeriodApprovalService}=require('../src/application/services/period-approval.service'),{PeriodExportService}=require('../src/application/services/period-export.service'),{TimeCorrectionService}=require('../src/application/services/time-correction.service');
const {PermissionsGuard}=require('../src/adapters/guards/permissions.guard'),{TimeCorrectionController}=require('../src/adapters/controllers/time-correction.controller');
const {pinLookupDigest,pinLookupKeyFingerprint,kioskClientDigest}=require('../src/infrastructure/security/pin-lookup'),{encryptPin,decryptPin}=require('../src/infrastructure/security/pin-encryption.util'),{backfillPinLookup}=require('../src/infrastructure/security/pin-lookup-backfill');
const db=new PrismaClient(),auth=new AuthorizationService(),onboard=new OnboardingService(db,auth),staff=new StaffService(db,auth),periods=new PeriodApprovalService(db,auth),exportsSvc=new PeriodExportService(db),corrections=new TimeCorrectionService(db,auth);
const redis=new RedisService(new ConfigService()),tag=crypto.randomUUID().slice(0,8),all=['TIME_VIEW','TIME_APPROVE','TIME_EDIT','STAFF_VIEW','STAFF_CREATE','STAFF_EDIT','PROPERTY_MANAGE','RESET_EMPLOYEE_PIN'];
let ca,cb,pa,pb,pc,da,dbb,posa,posb,admin,w1,w2,period,legacy,lastShift;
const actor=role=>({...admin,role,companyId:ca.id,assignedLocationIds:[pa.id],permissions:all});
const dto=(suffix,pin,extra={})=>({firstName:'Integration',lastName:suffix,employeeNumber:'EMP-IT-'+tag+'-'+suffix,pinCode:pin,propertyId:pa.id,departmentId:da.id,positionId:posa.id,effectiveFrom:'2020-01-01T00:00:00Z',...extra});
const identify=(pin,client='integration-'+tag,property=pa)=>attendance.identifyKioskPin({pin_code:pin,property_id:property.id},client);
const attendance=new AttendanceService(db,redis,new WorkShiftService(db,auth));
before(async()=>{
 assert.equal((await db.$queryRawUnsafe('SELECT current_database() AS name'))[0].name,'nexustaff_test');
 redis.onModuleInit();await new Promise(r=>setTimeout(r,150));await redis.ping();
 ca=await db.company.create({data:{name:'IT '+tag,taxId:'IT-'+tag}});cb=await db.company.create({data:{name:'Foreign '+tag,taxId:'F-'+tag}});
 admin=await db.user.create({data:{companyId:ca.id,email:tag+'@integration.invalid',firstName:'Integration',lastName:'Admin',employeeNumber:'ADM-'+tag,passwordHash:'not-login',role:'SUPER_ADMIN'}});
 async function property(c,name){return db.location.create({data:{companyId:c.id,name:name+' '+tag,locationCode:name+'-'+tag,address:'Test',timezone:'America/New_York'}});}
 pa=await property(ca,'A');pb=await property(ca,'B');pc=await property(cb,'C');da=await onboard.createDepartment(pa.id,{name:'Operations',code:'OPS'},admin);dbb=await onboard.createDepartment(pb.id,{name:'Operations',code:'OPS'},admin);posa=await onboard.createPosition(pa.id,{departmentId:da.id,name:'Staff',code:'STAFF'},admin);posb=await onboard.createPosition(pb.id,{departmentId:dbb.id,name:'Staff',code:'STAFF'},admin);
});
after(async()=>{await redis.onModuleDestroy();for(const c of [ca,cb])if(c){await db.user.deleteMany({where:{companyId:c.id}});await db.company.delete({where:{id:c.id}});}await db.$disconnect();});
test('all eight local migrations including PIN index and review version applied',async()=>{const rows=await db.$queryRawUnsafe('SELECT migration_name FROM _prisma_migrations WHERE finished_at IS NOT NULL AND rolled_back_at IS NULL');assert.equal(rows.length,8);});
test('real dry/apply/repeat backfill initializes fingerprint and enrolls without resetting PIN',async()=>{
 legacy=await db.user.create({data:{companyId:ca.id,email:'legacy-'+tag+'@integration.invalid',firstName:'Legacy',lastName:'Test',employeeNumber:'EMP-L-'+tag,passwordHash:'not-login',pinCodeHash:await bcrypt.hash('817263',4),pinCodeEncrypted:encryptPin('817263'),role:'WORKER'}});
 const original=legacy.pinCodeHash;const dry=await backfillPinLookup(db);assert.equal(dry.invalidEncryptedRecords,0);assert.equal((await db.user.findUnique({where:{id:legacy.id}})).pinLookupDigest,null);await backfillPinLookup(db,true);const row=await db.user.findUnique({where:{id:legacy.id}});assert.equal(row.pinLookupDigest,pinLookupDigest('817263'));assert.equal(row.pinCodeHash,original);assert.equal((await db.pinLookupConfig.findUnique({where:{id:1}})).keyFingerprint,pinLookupKeyFingerprint());assert.equal((await backfillPinLookup(db)).overlappingConflicts,0);
});
test('duplicate onboarding conflicts roll back real user/assignment transaction',async()=>{w1=await onboard.create(dto('one','624810'),admin);await assert.rejects(onboard.create(dto('collision','624810'),admin),e=>e.getStatus()===409);assert.equal(await db.user.count({where:{employeeNumber:dto('collision','624810').employeeNumber}}),0);w2=await onboard.create(dto('two','725910'),admin);});
test('PIN reset synchronizes all credentials atomically; conflict rolls back',async()=>{const old=await db.user.findUnique({where:{id:w2.id}});await assert.rejects(staff.resetPin(w2.id,'624810',admin));assert.equal((await db.user.findUnique({where:{id:w2.id}})).pinCodeHash,old.pinCodeHash);await staff.resetPin(w2.id,'725911',admin);const row=await db.user.findUnique({where:{id:w2.id}});assert.equal(row.pinLookupDigest,pinLookupDigest('725911'));assert.ok(await bcrypt.compare('725911',row.pinCodeHash));assert.equal(decryptPin(row.pinCodeEncrypted),'725911');});
test('multi-property and disjoint same-PIN allowed; assignment collision rejected',async()=>{await onboard.add(w1.id,dto('unused','624810',{propertyId:pb.id,departmentId:dbb.id,positionId:posb.id}),admin);const other=await onboard.create(dto('branch','725911',{propertyId:pb.id,departmentId:dbb.id,positionId:posb.id}),admin);await assert.rejects(onboard.add(other.id,dto('unused','725911'),admin));assert.equal(await db.employeeAssignment.count({where:{userId:other.id,propertyId:pa.id}}),0);});
test('reactivation collision rejected and non-overlapping historical PIN reuse allowed',async()=>{const inactive=await onboard.create(dto('inactive','624810',{status:'TERMINATED'}),admin);await assert.rejects(staff.update(inactive.id,{status:'ACTIVE'},admin));assert.equal((await db.user.findUnique({where:{id:inactive.id}})).status,'TERMINATED');await onboard.create(dto('historic','624810',{effectiveFrom:'2018-01-01T00:00:00Z',effectiveUntil:'2018-01-02T00:00:00Z'}),admin);});
test('hash-only eligible staff and wrong lookup key fail closed',async()=>{const assignment=await db.employeeAssignment.create({data:{userId:legacy.id,propertyId:pa.id,departmentId:da.id,positionId:posa.id,effectiveFrom:new Date('2020-01-01')}});await db.user.update({where:{id:legacy.id},data:{pinLookupDigest:null,pinCodeEncrypted:null}});await assert.rejects(identify('624810'),e=>e.getStatus()===503);await db.employeeAssignment.delete({where:{id:assignment.id}});const saved=process.env.PIN_LOOKUP_KEY;process.env.PIN_LOOKUP_KEY=crypto.randomBytes(32).toString('hex');try{await assert.rejects(identify('624810'),e=>e.getStatus()===503);}finally{process.env.PIN_LOOKUP_KEY=saved;}});
test('real Redis per-client budget persists after success and blocks only that client',async()=>{const client='budget-'+tag;await identify('624810',client);assert.equal(await redis.getFailedAttempts('kiosk_client:'+kioskClientDigest(client),true),1);for(let i=1;i<60;i++)await redis.incrementFailedAttempts('kiosk_client:'+kioskClientDigest(client),60,true);await assert.rejects(identify('624810',client));assert.ok(await identify('624810','another-'+tag));});
test('real Redis property/digest limit and employee lockout preserve unrelated workers',async()=>{for(let i=0;i<5;i++)await assert.rejects(identify('000000','wrong-'+tag));assert.equal(await redis.getFailedAttempts('kiosk_hint:'+pa.id+':'+pinLookupDigest('000000'),true),5);assert.ok(await identify('624810','good-'+tag));const number=dto('one','624810').employeeNumber;for(let i=0;i<5;i++)await redis.incrementFailedAttempts('kiosk_pin:'+number,900,true);await assert.rejects(identify('624810','locked-'+tag));assert.ok(await identify('725911','other-'+tag));await redis.resetFailedAttempts('kiosk_pin:'+number,true);});
test('actual disconnected Redis causes safe authentication failure',async()=>{const unavailable=new RedisService(new ConfigService());unavailable.onModuleInit();await new Promise(r=>setTimeout(r,100));await unavailable.onModuleDestroy();const svc=new AttendanceService(db,unavailable,new WorkShiftService(db,auth));await assert.rejects(svc.identifyKioskPin({pin_code:'624810',property_id:pa.id},'down-'+tag),e=>e.getStatus()===503);});
test('600 real shifts and 1200 events export beyond page boundaries',async()=>{const shifts=[],logs=[];for(let i=0;i<600;i++){const id=crypto.randomUUID(),clockInTimestamp=new Date(Date.UTC(2026,0,5,12,0)+i*120000),clockOutTimestamp=new Date(+clockInTimestamp+60000);shifts.push({id,userId:w1.id,locationId:pa.id,departmentId:da.id,positionId:posa.id,clockInTimestamp,clockOutTimestamp,status:'COMPLETED',regularMinutes:1,overtimeMinutes:0});logs.push({id:crypto.randomUUID(),userId:w1.id,locationId:pa.id,workShiftId:id,timestamp:clockInTimestamp,punchType:'CLOCK_IN'},{id:crypto.randomUUID(),userId:w1.id,locationId:pa.id,workShiftId:id,timestamp:clockOutTimestamp,punchType:'CLOCK_OUT'});}await db.workShift.createMany({data:shifts});await db.attendanceLog.createMany({data:logs});lastShift=shifts[599];const csv=await exportsSvc.csv('detail',{period:'weekly',start_date:'2026-01-05',location_id:pa.id},admin);assert.equal(csv.toString().split('\r\n').length,601);assert.doesNotMatch(csv.toString(),/payRate|password|pinLookup/i);});
test('resolve/review real weekly period and configured ordered submission',async()=>{await periods.configure(pa.id,[{stepName:'Branch review',approverRole:'SUPERVISOR'},{stepName:'Final review',approverRole:'SUPER_ADMIN'}],admin);period=await periods.resolve(pa.id,'2026-01-05','weekly',admin);assert.equal((await periods.resolve(pa.id,'2026-01-05','weekly',admin)).id,period.id);await assert.rejects(periods.resolve(pa.id,'2026-01-05','biweekly',admin));const review=await periods.review(period.id,actor('SUPERVISOR'));assert.equal(review.rows[0].workedMinutes,600);await periods.submit(period.id,review.reviewToken,actor('SUPERVISOR'));await assert.rejects(periods.submit(period.id,review.reviewToken,actor('SUPERVISOR')));});
test('real concurrent approval has exactly one winner and advances configured step',async()=>{let r=await periods.review(period.id,admin),s=r.rows[0];await assert.rejects(periods.transition(s.timesheetId,s.version,'APPROVE','',admin));const attempts=await Promise.allSettled([1,2].map(()=>periods.transition(s.timesheetId,s.version,'APPROVE','Reviewed',actor('SUPERVISOR'))));assert.equal(attempts.filter(r=>r.status==='fulfilled').length,1);r=await periods.review(period.id,admin);assert.equal(r.rows[0].status,'IN_REVIEW');await periods.transition(r.rows[0].timesheetId,r.rows[0].version,'APPROVE','Final',admin);assert.equal((await periods.review(period.id,admin)).period.status,'CLOSED');const csv=(await exportsSvc.csv('summary',{period:'weekly',start_date:'2026-01-05',location_id:pa.id},admin)).toString();assert.match(csv,/APPROVED/);});
test('approved correction atomically invalidates period and requires all steps again',async()=>{const request=await corrections.createCorrectionRequest({location_id:pa.id,work_shift_id:lastShift.id,correction_type:'INCORRECT_CLOCK_OUT',requested_timestamp:new Date(+lastShift.clockOutTimestamp+60000).toISOString(),reason:'Test correction'},admin);await corrections.approveCorrectionRequest(request.id,{comments:'Verified'},actor('LOCATION_ADMIN'));const r=await periods.review(period.id,admin);assert.equal(r.rows[0].status,'CORRECTION_REQUIRED');assert.equal(r.rows[0].workedMinutes,601);assert.equal(r.period.status,'OPEN');assert.match((await exportsSvc.csv('detail',{period:'weekly',start_date:'2026-01-05',location_id:pa.id},admin)).toString(),/CORRECTION_REQUIRED/);await periods.submit(period.id,r.reviewToken,actor('SUPERVISOR'));assert.equal((await periods.review(period.id,admin)).rows[0].currentStepOrder,1);});
for(const role of ['SUPER_ADMIN','OWNER','ADMIN','MANAGER','LOCATION_ADMIN','SUPERVISOR','WORKER'])test('real scope and correction guard regression '+role,async()=>{const a=actor(role);if(role==='WORKER'){await assert.rejects(periods.review(period.id,a));return;}assert.ok(await periods.review(period.id,a));if(!['SUPER_ADMIN','OWNER'].includes(role))await assert.rejects(periods.list(pb.id,a));if(role!=='SUPER_ADMIN')await assert.rejects(periods.list(pc.id,{...a,assignedLocationIds:[pc.id]}));const req=await corrections.createCorrectionRequest({location_id:pa.id,work_shift_id:lastShift.id,correction_type:'INCORRECT_CLOCK_OUT',requested_timestamp:new Date(+lastShift.clockOutTimestamp+120000).toISOString(),reason:'Scoped review'},admin);const guard=new PermissionsGuard(new Reflector(),auth,db);const context={getHandler:()=>TimeCorrectionController.prototype.reject,getClass:()=>TimeCorrectionController,switchToHttp:()=>({getRequest:()=>({user:a,params:{id:req.id},headers:{},query:{}})})};assert.equal(await guard.canActivate(context),true);await corrections.rejectCorrectionRequest(req.id,{comments:'No change'},a);const foreign={...a,companyId:cb.id,assignedLocationIds:[pa.id]};if(role!=='SUPER_ADMIN')await assert.rejects(corrections.rejectCorrectionRequest(req.id,{},foreign));});
test('reject and correction-required transitions record notes and permit fresh resubmission',async()=>{let r=await periods.review(period.id,admin),s=r.rows[0];await periods.transition(s.timesheetId,s.version,'REJECT','Fix evidence',actor('SUPERVISOR'));r=await periods.review(period.id,admin);assert.equal(r.rows[0].status,'REJECTED');await periods.submit(period.id,r.reviewToken,actor('SUPERVISOR'));r=await periods.review(period.id,admin);s=r.rows[0];await periods.transition(s.timesheetId,s.version,'CORRECTION_REQUIRED','Please review',actor('SUPERVISOR'));assert.equal((await periods.review(period.id,admin)).rows[0].status,'CORRECTION_REQUIRED');});

test('log-only correction resolves canonical shift and invalidates approved review safely',async()=>{const log=await db.attendanceLog.findFirst({where:{workShiftId:lastShift.id,punchType:'CLOCK_OUT'}});const request=await corrections.createCorrectionRequest({location_id:pa.id,attendance_log_id:log.id,correction_type:'INCORRECT_CLOCK_OUT',requested_timestamp:new Date(+lastShift.clockOutTimestamp+180000).toISOString(),reason:'Log linked correction'},admin);await corrections.approveCorrectionRequest(request.id,{comments:'Verified canonical link'},actor('ADMIN'));const shift=await db.workShift.findUnique({where:{id:lastShift.id}});assert.equal(+shift.effectiveClockOut,+lastShift.clockOutTimestamp+180000);assert.equal(shift.regularMinutes,4);});
test('biweekly calendar boundaries and display follow property timezone',async()=>{const p=await periods.resolve(pb.id,'2026-03-02','biweekly',admin);assert.equal(+p.endDate+1-+p.startDate,14*86400000-3600000);const list=await periods.list(pb.id,admin);assert.equal(list[0].startDateLabel,'2026-03-02');assert.equal(list[0].endDateLabel,'2026-03-15');});

test('correction guard rejects worker even with claimed permission and rejects mismatched property claims',async()=>{const request=await corrections.createCorrectionRequest({location_id:pa.id,work_shift_id:lastShift.id,correction_type:'INCORRECT_CLOCK_OUT',requested_timestamp:new Date(+lastShift.clockOutTimestamp+240000).toISOString(),reason:'Guard check'},admin);const guard=new PermissionsGuard(new Reflector(),auth,db);const ctx=(user,headers)=>({getHandler:()=>TimeCorrectionController.prototype.approve,getClass:()=>TimeCorrectionController,switchToHttp:()=>({getRequest:()=>({user,params:{id:request.id},headers,query:{}})})});assert.throws(()=>guard.canActivate(ctx(actor('WORKER'),{})));await assert.rejects(guard.canActivate(ctx(actor('SUPERVISOR'),{'x-property-id':pb.id})));await assert.rejects(corrections.approveCorrectionRequest(request.id,{},actor('WORKER')));await corrections.rejectCorrectionRequest(request.id,{},admin);});
test('correction invalidates peer approvals in the same period, allowing atomic whole-period resubmission',async()=>{await periods.configure(pb.id,[{stepName:'Final',approverRole:'SUPER_ADMIN'}],admin);const p=await periods.resolve(pb.id,'2026-02-02','weekly',admin);const shifts=[];for(const [i,u] of [w1,w2].entries())shifts.push(await db.workShift.create({data:{userId:u.id,locationId:pb.id,clockInTimestamp:new Date('2026-02-02T14:00:00Z'),clockOutTimestamp:new Date('2026-02-02T15:00:00Z'),status:'COMPLETED',regularMinutes:60,overtimeMinutes:0}}));let review=await periods.review(p.id,admin);await periods.submit(p.id,review.reviewToken,admin);review=await periods.review(p.id,admin);for(const row of review.rows)await periods.transition(row.timesheetId,row.version,'APPROVE','Verified',admin);const request=await corrections.createCorrectionRequest({location_id:pb.id,work_shift_id:shifts[0].id,correction_type:'INCORRECT_CLOCK_OUT',requested_timestamp:'2026-02-02T15:01:00Z',reason:'Reopen peers'},admin);await corrections.approveCorrectionRequest(request.id,{},admin);review=await periods.review(p.id,admin);assert.equal(review.rows.length,2);assert.ok(review.rows.every(r=>r.status==='CORRECTION_REQUIRED'));await periods.submit(p.id,review.reviewToken,admin);assert.ok((await periods.review(p.id,admin)).rows.every(r=>r.status==='SUBMITTED'));});
