const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),bcrypt=require('bcrypt');
const {bootstrap,input,safeFailure}=require('./bootstrap-admin.cjs');
const {startup,runtimeEnv,runNode}=require('./startup.cjs');
const env={BOOTSTRAP_ADMIN_ON_START:'true',BOOTSTRAP_EMAIL:'initial@example.invalid',BOOTSTRAP_PASSWORD:'Ax9!'+crypto.randomBytes(24).toString('hex'),BOOTSTRAP_FIRST_NAME:'Initial',BOOTSTRAP_LAST_NAME:'Admin',BOOTSTRAP_EMPLOYEE_NUMBER:'ADM-BOOT',BOOTSTRAP_COMPANY_NAME:'Initial company',BOOTSTRAP_COMPANY_TAX_ID:'TEST-ID'};
function database(){let state={users:[],companies:[],markers:[]};let failMarker=false;const tx={$executeRawUnsafe:async sql=>assert.match(sql,/pg_advisory_xact_lock/),user:{count:async()=>state.users.length,findFirst:async()=>state.users[0]?{...state.users[0],company:state.companies.find(c=>c.id===state.users[0].companyId)}:null,create:async({data})=>{const u={id:'u',...data};state.users.push(u);return u;}},company:{count:async()=>state.companies.length,create:async({data})=>{const c={id:'c',...data};state.companies.push(c);return c;}},auditLog:{findFirst:async({where})=>state.markers.find(m=>m.actorId===where.actorId&&m.action===where.action&&m.targetEntity===where.targetEntity)||null,create:async({data})=>{if(failMarker)throw Error('private SQL');state.markers.push(data);return data;}}};return{get state(){return state;},set failMarker(value){failMarker=value;},$transaction:async fn=>{const before=structuredClone(state);try{return await fn(tx);}catch(e){state=before;throw e;}}};}
function harness(db,e=env){const calls=[],logs=[];return{calls,logs,run:()=>startup(e,{migrate:async()=>calls.push('migrate'),initialize:async()=>{calls.push('bootstrap');return bootstrap(db,e,{onStart:true});},start:async()=>calls.push('start'),log:m=>logs.push(m),error:m=>logs.push(m)})};}
for(const flag of [undefined,'false','TRUE','1'])test(`flag ${flag}: migrations then normal application, no bootstrap`,async()=>{const h=harness(database(),{BOOTSTRAP_ADMIN_ON_START:flag});assert.equal(await h.run(),0);assert.deepEqual(h.calls,['migrate','start']);});
for(const key of Object.keys(env).filter(k=>k!=='BOOTSTRAP_ADMIN_ON_START'))test(`missing ${key} fails safely without starting application`,async()=>{const h=harness(database(),{...env,[key]:''});assert.equal(await h.run(),1);assert.deepEqual(h.calls,['migrate','bootstrap']);assert.ok(h.logs.includes(`Missing required variable: ${key}`));assert.ok(!h.logs.join().includes(env.BOOTSTRAP_PASSWORD));});
test('fresh initialization hashes password, creates correct role/company and records completion; second start safely skips',async()=>{const db=database(),h=harness(db);assert.equal(await h.run(),0);assert.deepEqual(h.calls,['migrate','bootstrap','start']);const u=db.state.users[0];assert.equal(u.role,'SUPER_ADMIN');assert.equal(u.status,'ACTIVE');assert.equal(u.companyId,db.state.companies[0].id);assert.notEqual(u.passwordHash,env.BOOTSTRAP_PASSWORD);assert.equal(await bcrypt.compare(env.BOOTSTRAP_PASSWORD,u.passwordHash),true);assert.equal(db.state.markers.length,1);const before=structuredClone(db.state);const again=harness(db);assert.equal(await again.run(),0);assert.deepEqual(db.state,before);assert.ok(again.logs.includes('Initial administrator already exists; bootstrap skipped.'));assert.ok(![...h.logs,...again.logs].join().includes(env.BOOTSTRAP_PASSWORD));});
test('unexpected populated database fails closed',async()=>{const db=database();db.state.companies.push({id:'foreign'});const h=harness(db);assert.equal(await h.run(),1);assert.ok(!h.calls.includes('start'));assert.equal(db.state.users.length,0);});
test('matching manually created admin without startup provenance is not silently accepted',async()=>{const db=database();await bootstrap(db,env);const h=harness(db);assert.equal(await h.run(),1);assert.ok(!h.calls.includes('start'));});
test('changed identity/password/status and extra users/companies refuse reuse without overwrites',async()=>{const db=database();await bootstrap(db,env,{onStart:true});for(const change of [{BOOTSTRAP_EMAIL:'other@example.invalid'},{BOOTSTRAP_PASSWORD:'Bx8!'+crypto.randomBytes(24).toString('hex')},{BOOTSTRAP_COMPANY_TAX_ID:'OTHER'},{BOOTSTRAP_FIRST_NAME:'Other'}]){const before=structuredClone(db.state);assert.equal(await harness(db,{...env,...change}).run(),1);assert.deepEqual(db.state,before);}db.state.users[0].status='TERMINATED';assert.equal(await harness(db).run(),1);db.state.users[0].status='ACTIVE';db.state.users.push({id:'extra'});assert.equal(await harness(db).run(),1);db.state.users.pop();db.state.companies.push({id:'extra'});assert.equal(await harness(db).run(),1);});
test('audit completion failure rolls back company and admin with the same transaction',async()=>{const db=database();db.failMarker=true;assert.equal(await harness(db).run(),1);assert.deepEqual(db.state,{users:[],companies:[],markers:[]});});
test('migration failure never starts bootstrap or Nest and masks raw failure',async()=>{const logs=[];let next=false;assert.equal(await startup(env,{migrate:async()=>{throw Error(env.BOOTSTRAP_PASSWORD);},initialize:async()=>{next=true;},start:async()=>{next=true;},error:m=>logs.push(m)}),1);assert.equal(next,false);assert.deepEqual(logs,['Database migrations failed; application not started.']);});
test('weak passwords still fail and arbitrary errors never expose values',()=>{assert.throws(()=>input({...env,BOOTSTRAP_PASSWORD:'short'}));assert.ok(!safeFailure(Error(env.BOOTSTRAP_PASSWORD)).includes(env.BOOTSTRAP_PASSWORD));});
test('bootstrap credentials are excluded from child processes',()=>{assert.deepEqual(runtimeEnv({...env,DATABASE_URL:'fixture',PORT:'3001'}),{DATABASE_URL:'fixture',PORT:'3001'});});
test('portable Node process runner waits for success and propagates failure without shell',async()=>{await runNode('-e',['process.exit(0)'],process.env,true);await assert.rejects(runNode('-e',['process.exit(3)'],process.env,true));});
