const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),Module=require('module'),ts=require('typescript');
for(const ext of ['.ts','.tsx'])require.extensions[ext]=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true,target:ts.ScriptTarget.ES2022}}).outputText,f);
const resolve=Module._resolveFilename;Module._resolveFilename=function(r,...a){return resolve.call(this,r.startsWith('@/')?path.resolve(__dirname,'../src',r.slice(2)):r,...a);};const React=require('react');
let state=[],refs=[],cursor=0,refCursor=0,calls=[],user;
const catalog={companies:[{id:'c',name:'Company'}],roles:['MANAGER','LOCATION_ADMIN','SUPERVISOR'],canCreate:true,properties:[{id:'a',name:'Branch A',companyId:'c',canCreate:true,canEdit:true,permissions:['TIME_VIEW']}]};
const api={catalog:async()=>catalog,list:async()=>[],create:async data=>calls.push(data),update:async(id,data)=>calls.push({id,...data}),reset:async(...args)=>calls.push(args)};
const load=Module._load;Module._load=function(r,...a){if(r==='react')return {...React,useState(initial){const i=cursor++;if(!(i in state))state[i]=typeof initial==='function'?initial():initial;return[state[i],v=>state[i]=typeof v==='function'?v(state[i]):v];},useRef(initial){const i=refCursor++;if(!(i in refs))refs[i]={current:initial};return refs[i];},useEffect:()=>{}};if(r==='@/store/use-auth-store')return{useAuthStore:()=>({user,token:'test'})};if(r==='@/lib/api-client')return{adminAccountsApi:api};return load.call(this,r,...a);};
const Page=require('../src/app/admin/(protected)/access/page').default;
function tree(){cursor=refCursor=0;return Page();}function nodes(n,p){if(!n||typeof n!=='object')return[];return[...(p(n)?[n]:[]),...React.Children.toArray(n.props?.children).flatMap(c=>nodes(c,p))];}function button(name){return nodes(tree(),n=>n.type==='button'&&n.props.children===name)[0];}
function init(){state=[];refs=[];calls=[];user={id:'owner',role:'OWNER',companyId:'c',permissions:[]};tree();state[0]=catalog;}
test('actual form uses catalog roles, scoped branch selectors and password input',()=>{init();button('+ Add Admin Account').props.onClick();assert.deepEqual(nodes(tree(),n=>n.type==='select'&&n.props['aria-label']==='Account role')[0].props.children.map(x=>x.props.value),catalog.roles);const input=nodes(tree(),n=>n.props?.['aria-label']==='Temporary password')[0];assert.equal(input.props.type,'password');assert.equal(input.props.autoComplete,'new-password');});
test('cancel clears temporary credentials',()=>{init();button('+ Add Admin Account').props.onClick();state[3]='temporary';button('Cancel').props.onClick();assert.equal(state[3],'');assert.equal(state[2],null);});
test('submit clears password before API completes and update sends only writable fields',async()=>{init();state[2]={id:'u',firstName:'A',lastName:'B',email:'a@b.test',role:'MANAGER',companyId:'c',status:'ACTIVE',grants:[],version:'v',canEdit:true,passwordHash:'must-not-send'};state[3]='temporary';await nodes(tree(),n=>n.type==='form')[0].props.onSubmit({preventDefault(){}});assert.equal(state[3],'');assert.equal(calls[0].canEdit,undefined);assert.equal(calls[0].passwordHash,undefined);assert.equal(calls[0].password,undefined);assert.equal(calls[0].version,'v');});
test('company change removes stale branch grants',()=>{init();button('+ Add Admin Account').props.onClick();state[2].grants=[{propertyId:'a',permissions:['TIME_VIEW']}];nodes(tree(),n=>n.props?.['aria-label']==='Account company')[0].props.onChange({target:{value:'other'}});assert.deepEqual(state[2].grants,[]);});
test('WORKER denied and protected account exposes no mutation controls',()=>{init();state[1]=[{id:'s',firstName:'Platform',lastName:'Admin',email:'s@test.invalid',role:'SUPER_ADMIN',grants:[],legacyPropertyIds:[],globalPermissions:[],status:'ACTIVE',canEdit:false,canReset:false}];assert.equal(button('Edit'),undefined);assert.equal(button('Reset password'),undefined);user={role:'WORKER'};assert.equal(tree().props.role,'alert');});
