const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),Module=require('module'),ts=require('typescript'),React=require('react');
let state,refs,cursor,refCursor,effect,calls,value,failRead,failSave,changes;
const api={getPolicy:async id=>{calls.push(['GET',id]);if(failRead)throw Error('Unavailable');return{requireApproval:value};},policy:async(id,required)=>{calls.push(['POST',id,required]);if(failSave)throw Error('Unavailable');value=required;}};
const load=Module._load;Module._load=function(r,...a){if(r==='react')return {...React,useState(initial){const i=cursor++;if(!(i in state))state[i]=initial;return[state[i],v=>state[i]=v];},useRef(initial){const i=refCursor++;return refs[i]||=( {current:initial} );},useEffect:fn=>effect=fn};if(r==='@/lib/api-client')return{periodApprovalApi:api};return load.call(this,r,...a);};
const file=path.resolve(__dirname,'../src/components/reports/branch-approval-policy.tsx'),m=new Module(file,module);m.filename=file;m.paths=module.paths;m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText,file);const {BranchApprovalPolicy}=m.exports;
function tree(){cursor=refCursor=0;return BranchApprovalPolicy({locationId:'branch-a',onChanged:async()=>changes++});}
function nodes(n,p){if(!n||typeof n!=='object')return[];return[...(p(n)?[n]:[]),...React.Children.toArray(n.props?.children).flatMap(c=>nodes(c,p))];}
const checkbox=()=>nodes(tree(),n=>n.type==='input')[0];const tick=()=>new Promise(r=>setImmediate(r));
function init(){state=[];refs=[];calls=[];value=false;failRead=failSave=false;changes=0;tree();}
test('no period required: loading disabled, persisted OFF loaded and POST/readback survives remount',async()=>{init();assert.equal(checkbox().props.disabled,true);effect();await tick();assert.equal(checkbox().props.checked,false);assert.equal(checkbox().props.disabled,false);checkbox().props.onChange({target:{checked:true}});assert.equal(checkbox().props.disabled,true);await tick();assert.deepEqual(calls,[['GET','branch-a'],['POST','branch-a',true],['GET','branch-a']]);assert.equal(checkbox().props.checked,true);assert.equal(changes,1);state=[];refs=[];tree();effect();await tick();assert.equal(checkbox().props.checked,true);});
test('read failure stays unavailable, disabled, and retries persisted state',async()=>{init();failRead=true;effect();await tick();assert.equal(checkbox().props.disabled,true);assert.equal(nodes(tree(),n=>n.props.role==='alert').length,1);failRead=false;await nodes(tree(),n=>n.type==='button')[0].props.onClick();assert.equal(checkbox().props.disabled,false);assert.equal(checkbox().props.checked,false);});
test('save failure never leaves a fake new value and unmount ignores late readback',async()=>{init();const cleanup=effect();await tick();failSave=true;checkbox().props.onChange({target:{checked:true}});await tick();assert.equal(state[0],null);assert.equal(checkbox().props.disabled,true);assert.equal(value,false);failSave=false;cleanup();value=true;await nodes(tree(),n=>n.type==='button')[0].props.onClick();assert.equal(state[0],null);});
