const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),Module=require('module'),ts=require('typescript');
for(const ext of ['.ts','.tsx'])require.extensions[ext]=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true,target:ts.ScriptTarget.ES2022}}).outputText,f);
const resolve=Module._resolveFilename;Module._resolveFilename=function(r,...a){return resolve.call(this,r.startsWith('@/')?path.resolve(__dirname,'../src',r.slice(2)):r,...a);};
const React=require('react'),{renderToStaticMarkup}=require('react-dom/server');
let state=[],refs=[],cursor=0,refCursor=0,effects=[],calls=[],redirected,answer=async()=>new Blob(['complete period']),scope='ALL',user={id:'admin',role:'SUPER_ADMIN'};
const load=Module._load;Module._load=function(r,...a){
 if(r==='react')return {...React,useState(initial){const i=cursor++;if(!(i in state))state[i]=typeof initial==='function'?initial():initial;return[state[i],v=>state[i]=typeof v==='function'?v(state[i]):v];},useRef(initial){const i=refCursor++;if(!(i in refs))refs[i]={current:initial};return refs[i];},useEffect:fn=>effects.push(fn)};
 if(r==='next/navigation')return{redirect:path=>{redirected=path;},useRouter:()=>({}),usePathname:()=>'/admin'};
 if(r==='next/link')return({children,...props})=>React.createElement('a',props,children);
 if(r==='@/store/use-auth-store')return{useAuthStore:()=>({user,token:'test-only'})};
 if(r==='@/store/use-location-store')return{useLocationStore:()=>({selectedLocationId:scope,locations:[{id:'a',name:'Allowed',code:'A'}],fetchLocations:()=>{},setSelectedLocationId:()=>{}})};
 if(r==='@/lib/api-client')return{reportsApi:{periodCsv:async(kind,params)=>{calls.push({kind,params});return answer();}},staffApi:{list:async()=>[]}};
 return load.call(this,r,...a);
};
const {PeriodExports}=require('../src/components/reports/period-exports');
const {periodParameters}=require('../src/lib/export-period');
function tree(){cursor=refCursor=0;effects=[];return PeriodExports();}
function nodes(node,predicate){if(!node||typeof node!=='object')return[];return[...(predicate(node)?[node]:[]),...React.Children.toArray(node.props?.children).flatMap(n=>nodes(n,predicate))];}
function initialize(){state=[];refs=[];calls=[];scope='a';user={id:'admin',role:'SUPER_ADMIN'};tree();state[1]='2026-01-01';answer=async()=>new Blob(['all rows']);}
function button(kind){return nodes(tree(),n=>n.type==='button')[kind==='detail'?0:1];}
test('root redirects to clock with no shared portal chooser',()=>{require('../src/app/page.tsx').default();assert.equal(redirected,'/clock');const root=fs.readFileSync(path.resolve(__dirname,'../src/app/page.tsx'),'utf8');assert.doesNotMatch(root,/Admin portal|Tablet kiosk|<Link/);});
test('admin login and sidebar have no employee-clock launcher; Settings bridge is labeled Terminal Setup',()=>{for(const file of ['app/admin/(auth)/login/page.tsx','components/admin/sidebar.tsx']){const text=fs.readFileSync(path.resolve(__dirname,'../src',file),'utf8');assert.doesNotMatch(text,/href="\/clock"|Open tablet kiosk|Staff clocking in/);}const settings=fs.readFileSync(path.resolve(__dirname,'../src/app/admin/(protected)/settings/page.tsx'),'utf8');assert.match(settings,/href="\/clock\/setup"/);assert.match(settings,/Terminal Setup/);});
test('clock keeps no admin sidebar or management content',()=>{const source=fs.readFileSync(path.resolve(__dirname,'../src/app/clock/page.tsx'),'utf8');assert.doesNotMatch(source,/Sidebar|Payroll|Staff Directory|href="\/admin/);assert.match(source,/href="\/clock\/setup"/);});
test('period params are scoped independently of UI pagination and validate custom dates',()=>{assert.deepEqual(periodParameters('weekly','2026-01-01','','ALL'),{period:'weekly',start_date:'2026-01-01'});assert.deepEqual(periodParameters('custom','2026-01-01','2026-01-14','a'),{period:'custom',start_date:'2026-01-01',end_date:'2026-01-14',location_id:'a'});assert.throws(()=>periodParameters('custom','2026-01-10','2026-01-01','a'));});
test('actual export controls fetch full server period then download returned blob',async()=>{initialize();let downloaded=0;const originalDocument=global.document,create=URL.createObjectURL,revoke=URL.revokeObjectURL;global.document={createElement:()=>({click:()=>downloaded++})};URL.createObjectURL=blob=>{assert.ok(blob instanceof Blob);return 'blob:test';};URL.revokeObjectURL=()=>{};try{await button('detail').props.onClick();assert.equal(downloaded,1);assert.deepEqual(calls[0],{kind:'detail',params:{period:'weekly',start_date:'2026-01-01',location_id:'a'}});assert.match(state[5],/Complete period export downloaded/);state[0]='custom';state[2]='2026-01-14';await button('summary').props.onClick();assert.equal(calls[1].params.end_date,'2026-01-14');}finally{global.document=originalDocument;URL.createObjectURL=create;URL.revokeObjectURL=revoke;}});
test('late export response after branch change is discarded',async()=>{initialize();let finish;answer=()=>new Promise(r=>finish=r);const request=button('detail').props.onClick();scope='b';tree();finish(new Blob(['old branch']));await request;assert.equal(state[5],'');});
test('export failure is visible and never fabricates a CSV',async()=>{initialize();answer=async()=>{throw Error('Period export unavailable');};await button('detail').props.onClick();assert.equal(state[4],'Period export unavailable');assert.equal(state[3],false);});
test('without TIME_VIEW export controls are absent and cannot request data',()=>{initialize();user={id:'s',role:'SUPERVISOR',companyId:'c',assignedLocationIds:['a'],permissions:[]};assert.equal(tree(),null);assert.equal(calls.length,0);});
test('branch selector lists authorized store results; TIME_VIEW allows reports without granting money permissions',()=>{const {LocationSwitcher}=require('../src/components/admin/location-switcher');const access=require('../src/lib/admin-access');user={id:'s',role:'SUPERVISOR',companyId:'c',assignedLocationIds:['a'],permissions:['PROPERTY_VIEW','TIME_VIEW']};const html=renderToStaticMarkup(React.createElement(LocationSwitcher));assert.match(html,/Allowed/);assert.doesNotMatch(html,/Foreign/);assert.equal(access.canOpenAdminRoute(user,'/admin/reports','a'),true);assert.equal(access.canOpenAdminRoute(user,'/admin/reports','foreign'),false);assert.equal(access.can(user,'VIEW_PAY_RATE','a'),false);});
test('both CSV filenames use safe Branch/date components and pass original Blob through unchanged',async()=>{const {reportFilename}=require('../src/lib/export-period');for(const kind of ['detail','summary'])assert.equal(reportFilename(kind,'Florida Beach','custom','2026-09-22','2026-09-23'),`NexuStaff_Florida-Beach_${kind==='detail'?'Attendance-Detail':'Period-Summary'}_2026-09-22_2026-09-23.csv`);for(const name of ['../../Branch\\bad:*?"<>|\u0000','Sucursal Centro - MÉRIDA','///']){const file=reportFilename('detail',name,'weekly','2026-09-22','');assert.doesNotMatch(file,/[\\/:*?"<>|\x00-\x1f]|\.\./);assert.match(file,/_2026-09-22_2026-09-28\.csv$/);}assert.match(reportFilename('summary',undefined,'biweekly','2026-09-22','',true),/All-Authorized-Branches.*2026-10-05.csv$/);initialize();state[0]='custom';state[1]='2026-09-22';state[2]='2026-09-23';const blob=new Blob(['a,b\r\n1,2\r\n']);answer=async()=>blob;const oldDoc=global.document,oldCreate=URL.createObjectURL,oldRevoke=URL.revokeObjectURL,links=[];global.document={createElement:()=>{const link={click(){}};links.push(link);return link;}};URL.createObjectURL=value=>{assert.equal(value,blob);return 'blob:unchanged';};URL.revokeObjectURL=()=>{};try{await button('detail').props.onClick();await button('summary').props.onClick();assert.equal(links[0].download,'NexuStaff_Allowed_Attendance-Detail_2026-09-22_2026-09-23.csv');assert.equal(links[1].download,'NexuStaff_Allowed_Period-Summary_2026-09-22_2026-09-23.csv');assert.equal(await blob.text(),'a,b\r\n1,2\r\n');}finally{global.document=oldDoc;URL.createObjectURL=oldCreate;URL.revokeObjectURL=oldRevoke;}});
