const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),Module=require('module'),ts=require('typescript');
for(const ext of ['.ts','.tsx'])require.extensions[ext]=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true,target:ts.ScriptTarget.ES2022}}).outputText,f);
const resolve=Module._resolveFilename;Module._resolveFilename=function(r,...a){return resolve.call(this,r.startsWith('@/')?path.resolve(__dirname,'../src',r.slice(2)):r,...a);};const React=require('react');
let state=[],refs=[],cursor=0,refCursor=0,calls=[],scope='a',user,reviewAnswer;
const api={list:async()=>[],resolve:async()=>({id:'p'}),review:async()=>reviewAnswer,submit:async(id,token)=>calls.push({id,token}),transition:async(...args)=>calls.push(args),configure:async()=>{}};
const load=Module._load;Module._load=function(r,...a){if(r==='react')return {...React,useState(initial){const i=cursor++;if(!(i in state))state[i]=typeof initial==='function'?initial():initial;return[state[i],v=>state[i]=typeof v==='function'?v(state[i]):v];},useRef(initial){const i=refCursor++;if(!(i in refs))refs[i]={current:initial};return refs[i];},useEffect:()=>{}};if(r==='@/store/use-auth-store')return{useAuthStore:()=>({user,token:'test'})};if(r==='@/store/use-location-store')return{useLocationStore:()=>({selectedLocationId:scope})};if(r==='@/lib/api-client')return{periodApprovalApi:api};return load.call(this,r,...a);};
const {PeriodReview}=require('../src/components/reports/period-review');
function tree(){cursor=refCursor=0;return PeriodReview();}function nodes(n,p){if(!n||typeof n!=='object')return[];return[...(p(n)?[n]:[]),...React.Children.toArray(n.props?.children).flatMap(c=>nodes(c,p))];}function button(name){return nodes(tree(),n=>n.type==='button'&&n.props.children===name)[0];}
function init(){state=[];refs=[];calls=[];scope='a';user={id:'s',role:'SUPERVISOR',companyId:'c',assignedLocationIds:['a'],permissions:['TIME_VIEW','TIME_APPROVE']};tree();reviewAnswer={period:{id:'p',status:'OPEN'},reviewToken:'review-evidence',orphanAttendance:0,rows:[{staff:{id:'u',firstName:'Staff'},workedMinutes:60,workedHours:1,incompleteShifts:0,pendingCorrections:0,correctionCount:0,status:'DRAFT',history:[],steps:[],version:0}]};state[1]=reviewAnswer;}
test('submitting actual review component sends server review token',async()=>{init();await button('Submit period').props.onClick();assert.deepEqual(calls,[{id:'p',token:'review-evidence'}]);});
test('Open period remains a styled native button with original resolve/load and disabled/loading behavior',async()=>{init();const open=()=>nodes(tree(),n=>n.type==='button'&&n.props['aria-label']==='Open period')[0];assert.equal(open().props.type,'button');assert.match(open().props.className,/admin-primary-button/);assert.equal(open().props.disabled,true);state[2]='2026-01-05';assert.equal(open().props.disabled,false);const old=api.resolve;let finish;api.resolve=(...args)=>{calls.push(args);return new Promise(r=>finish=r);};const request=open().props.onClick();assert.equal(open().props.disabled,true);assert.equal(open().props['aria-busy'],true);finish({id:'p'});await request;assert.deepEqual(calls,[['a','2026-01-05','weekly']]);assert.equal(state[1].period.id,'p');assert.equal(open().props.disabled,false);api.resolve=old;});
test('review component blocks incomplete/pending correction submission',()=>{init();state[1].rows[0].incompleteShifts=1;assert.equal(button('Submit period').props.disabled,true);state[1].rows[0].incompleteShifts=0;state[1].rows[0].pendingCorrections=1;assert.equal(button('Submit period').props.disabled,true);});
test('only configured step approver receives transition controls and sends version',async()=>{init();Object.assign(state[1].rows[0],{timesheetId:'s1',status:'SUBMITTED',version:3,currentStepOrder:1,steps:[{stepOrder:1,approverRole:'SUPERVISOR'}]});await button('Approve').props.onClick();assert.deepEqual(calls[0],['s1',3,'APPROVE','']);user={...user,role:'LOCATION_ADMIN'};assert.equal(button('Approve'),undefined);});
test('notes required for rejection and stale evidence blocks approval',()=>{init();Object.assign(state[1].rows[0],{timesheetId:'s1',status:'SUBMITTED',version:3,currentStepOrder:1,stale:true,steps:[{stepOrder:1,approverRole:'SUPERVISOR'}]});assert.equal(button('Approve').props.disabled,true);assert.equal(button('Reject').props.disabled,true);state[4]='Please correct';assert.equal(button('Reject').props.disabled,false);});
test('ALL requires branch choice and TIME_VIEW absence hides review',()=>{init();scope='ALL';assert.equal(button('Submit period'),undefined);user.permissions=[];scope='a';assert.equal(tree(),null);});
test('late review response after branch switch is discarded',async()=>{init();state[2]='2026-01-05';let finish;const original=api.review;api.review=()=>new Promise(r=>finish=r);const request=button('Refresh review').props.onClick();await new Promise(r=>setImmediate(r));scope='b';tree();finish({...reviewAnswer,period:{id:'wrong'}});await request;assert.equal(state[1].period.id,'p');api.review=original;});
test('optional approval disables submission and approval controls despite stored prior approval steps',()=>{init();state[1].requireApproval=false;Object.assign(state[1].rows[0],{status:'SUBMITTED',currentStepOrder:1,steps:[{stepOrder:1,approverRole:'SUPERVISOR'}]});assert.equal(button('Submit period').props.disabled,true);assert.equal(button('Approve'),undefined);});
test('company administrator sees branch policy without opening a period; ALL and reviewers do not',()=>{init();state[1]=null;user={...user,role:'SUPER_ADMIN'};const policy=()=>nodes(tree(),n=>typeof n.type==='function'&&n.type.name==='BranchApprovalPolicy');assert.equal(policy().length,1);scope='ALL';assert.equal(policy().length,0);scope='a';user={...user,role:'SUPERVISOR'};assert.equal(policy().length,0);});
test('review actions retain hierarchy, loading guard and configure payload',async()=>{init();user={...user,role:'OWNER'};const find=name=>nodes(tree(),n=>n.type==='button'&&n.props['aria-label']===name)[0];assert.match(find('Save approval workflow').props.className,/admin-secondary-button/);assert.match(find('Refresh review').props.className,/admin-secondary-button/);assert.match(find('Submit period').props.className,/admin-primary-button/);const original=api.configure;let finish;api.configure=(...args)=>{calls.push(args);return new Promise(r=>finish=r);};try{const pending=find('Save approval workflow').props.onClick();assert.equal(find('Refresh review').props.disabled,true);assert.equal(find('Save approval workflow').props['aria-busy'],true);await find('Refresh review').props.onClick();assert.equal(calls.length,1);finish();await pending;assert.equal(calls[0][0],'a');assert.equal(find('Refresh review').props.disabled,false);}finally{api.configure=original;}});
test('History shows explicit empty state or only real chronological audit events for every period state',()=>{const {ReviewHistory}=require('../src/components/reports/review-history');const html=value=>require('react-dom/server').renderToStaticMarkup(value);assert.match(html(ReviewHistory({history:[]})),/No review history yet/);for(const status of ['SUBMITTED','APPROVED','REJECTED','CORRECTION_REQUIRED']){const history=[{id:'b',createdAt:'2026-09-23T12:00Z',actor:{firstName:'Second',lastName:'Reviewer'},stepOrder:1,previousStatus:'SUBMITTED',newStatus:status,notes:'Real event'},{id:'a',createdAt:'2026-09-22T12:00Z',actor:{firstName:'First',lastName:'Reviewer'},stepOrder:1,previousStatus:'DRAFT',newStatus:'SUBMITTED'}];const element=ReviewHistory({history,timezone:'America/New_York'});assert.equal(element.type,'details');assert.equal(element.props.open,undefined);const markup=html(element);assert.ok(markup.indexOf('First Reviewer')<markup.indexOf('Second Reviewer'));assert.equal((markup.match(/<li>/g)||[]).length,2);assert.doesNotMatch(markup,/No review history yet/);assert.equal(history[0].id,'b');}});
