const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),Module=require('module'),ts=require('typescript');
for(const ext of ['.ts','.tsx'])require.extensions[ext]=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true,target:ts.ScriptTarget.ES2022}}).outputText,f);
const resolve=Module._resolveFilename;Module._resolveFilename=function(r,...a){return resolve.call(this,r.startsWith('@/')?path.resolve(__dirname,'../src',r.slice(2)):r,...a);};const React=require('react');
let state=[],refs=[],cursor=0,refCursor=0,calls=[],scope='a',user,reviewAnswer;
const api={list:async()=>[],resolve:async()=>({id:'p'}),review:async()=>reviewAnswer,submit:async(id,token)=>calls.push({id,token}),transition:async(...args)=>calls.push(args),configure:async()=>{}};
const load=Module._load;Module._load=function(r,...a){if(r==='react')return {...React,useState(initial){const i=cursor++;if(!(i in state))state[i]=typeof initial==='function'?initial():initial;return[state[i],v=>state[i]=typeof v==='function'?v(state[i]):v];},useRef(initial){const i=refCursor++;if(!(i in refs))refs[i]={current:initial};return refs[i];},useEffect:()=>{}};if(r==='@/store/use-auth-store')return{useAuthStore:()=>({user,token:'test'})};if(r==='@/store/use-location-store')return{useLocationStore:()=>({selectedLocationId:scope})};if(r==='@/lib/api-client')return{periodApprovalApi:api};return load.call(this,r,...a);};
const {PeriodReview}=require('../src/components/reports/period-review');
function tree(){cursor=refCursor=0;return PeriodReview();}function nodes(n,p){if(!n||typeof n!=='object')return[];return[...(p(n)?[n]:[]),...React.Children.toArray(n.props?.children).flatMap(c=>nodes(c,p))];}function button(name){return nodes(tree(),n=>n.type==='button'&&n.props.children===name)[0];}
function init(){state=[];refs=[];calls=[];scope='a';user={id:'s',role:'SUPERVISOR',companyId:'c',assignedLocationIds:['a'],permissions:['TIME_VIEW','TIME_APPROVE']};tree();reviewAnswer={period:{id:'p',status:'OPEN'},reviewToken:'review-evidence',orphanAttendance:0,rows:[{staff:{id:'u',firstName:'Staff'},workedMinutes:60,workedHours:1,incompleteShifts:0,pendingCorrections:0,correctionCount:0,status:'DRAFT',history:[],steps:[],version:0}]};state[1]=reviewAnswer;}
test('submitting actual review component sends server review token',async()=>{init();await button('Submit period').props.onClick();assert.deepEqual(calls,[{id:'p',token:'review-evidence'}]);});
test('review component blocks incomplete/pending correction submission',()=>{init();state[1].rows[0].incompleteShifts=1;assert.equal(button('Submit period').props.disabled,true);state[1].rows[0].incompleteShifts=0;state[1].rows[0].pendingCorrections=1;assert.equal(button('Submit period').props.disabled,true);});
test('only configured step approver receives transition controls and sends version',async()=>{init();Object.assign(state[1].rows[0],{timesheetId:'s1',status:'SUBMITTED',version:3,currentStepOrder:1,steps:[{stepOrder:1,approverRole:'SUPERVISOR'}]});await button('Approve').props.onClick();assert.deepEqual(calls[0],['s1',3,'APPROVE','']);user={...user,role:'LOCATION_ADMIN'};assert.equal(button('Approve'),undefined);});
test('notes required for rejection and stale evidence blocks approval',()=>{init();Object.assign(state[1].rows[0],{timesheetId:'s1',status:'SUBMITTED',version:3,currentStepOrder:1,stale:true,steps:[{stepOrder:1,approverRole:'SUPERVISOR'}]});assert.equal(button('Approve').props.disabled,true);assert.equal(button('Reject').props.disabled,true);state[4]='Please correct';assert.equal(button('Reject').props.disabled,false);});
test('ALL requires branch choice and TIME_VIEW absence hides review',()=>{init();scope='ALL';assert.equal(button('Submit period'),undefined);user.permissions=[];scope='a';assert.equal(tree(),null);});
test('late review response after branch switch is discarded',async()=>{init();state[2]='2026-01-05';let finish;const original=api.review;api.review=()=>new Promise(r=>finish=r);const request=button('Refresh review').props.onClick();await new Promise(r=>setImmediate(r));scope='b';tree();finish({...reviewAnswer,period:{id:'wrong'}});await request;assert.equal(state[1].period.id,'p');api.review=original;});
test('optional approval disables submission and approval controls despite stored prior approval steps',()=>{init();state[1].requireApproval=false;Object.assign(state[1].rows[0],{status:'SUBMITTED',currentStepOrder:1,steps:[{stepOrder:1,approverRole:'SUPERVISOR'}]});assert.equal(button('Submit period').props.disabled,true);assert.equal(button('Approve'),undefined);});
test('company administrator persists approval policy and reloads server review',async()=>{init();user={...user,role:'OWNER'};api.policy=async(id,required)=>{calls.push({id,required});reviewAnswer={...reviewAnswer,requireApproval:required};};const checkbox=nodes(tree(),n=>n.type==='input'&&n.props.type==='checkbox')[0];assert.ok(checkbox);checkbox.props.onChange({target:{checked:false}});await new Promise(r=>setImmediate(r));assert.deepEqual(calls,[{id:'a',required:false}]);assert.equal(state[1].requireApproval,false);});
