const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),Module=require('module'),ts=require('typescript');
for(const ext of ['.ts','.tsx'])require.extensions[ext]=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true,target:ts.ScriptTarget.ES2022}}).outputText,f);
const resolve=Module._resolveFilename;Module._resolveFilename=function(r,...a){return resolve.call(this,r.startsWith('@/')?path.resolve(__dirname,'../src',r.slice(2)):r,...a);};
const React=require('react'),{renderToStaticMarkup}=require('react-dom/server');let cursor=0,values={};const load=Module._load;
Module._load=function(r,...a){if(r==='react')return {...React,useState(initial){const i=cursor++;return [i in values?values[i]:typeof initial==='function'?initial():initial,()=>{}];},useRef:()=>({current:0}),useEffect:()=>{}};if(r==='@/store/use-auth-store')return {useAuthStore:()=>({user:{role:'SUPER_ADMIN'},token:'test-fixture'})};if(r==='@/store/use-location-store')return {useLocationStore:()=>({selectedLocationId:'ALL'})};if(r==='@/lib/api-client')return {staffApi:{},locationsApi:{},onboardingApi:{}};return load.call(this,r,...a);};
const Page=require('../src/app/admin/(protected)/employees/page.tsx').default;
const detail={id:'u',firstName:'Actual',lastName:'Worker',employeeNumber:'EMP-TEST',status:'ACTIVE',assignments:[],readiness:[{propertyId:'p',name:'Property',clockReady:false,canEdit:false}],canViewPin:false,canResetPin:false};
function render(v){values=v;cursor=0;return renderToStaticMarkup(Page());}
test('server readiness false is Assignment Required despite active employee',()=>{const html=render({2:detail});assert.match(html,/Assignment Required/);assert.doesNotMatch(html,/>Clock Ready</);});
test('server PIN capability flags hide view/reset and any recovered value',()=>{const html=render({2:detail,12:'DO-NOT-DISPLAY'});assert.doesNotMatch(html,/View PIN|Reset PIN|DO-NOT-DISPLAY/);});
test('authorized admin has explicit PIN view/reset actions and real Clock Ready status',()=>{const html=render({2:{...detail,canViewPin:true,canResetPin:true,readiness:[{...detail.readiness[0],clockReady:true}]}});assert.match(html,/View PIN/);assert.match(html,/Reset PIN/);assert.match(html,/>Clock Ready</);});
test('department selection filters position options and offers no invented rates',()=>{const html=render({4:'create',5:{propertyId:'p',departmentId:'d',positionId:'',effectiveFrom:'2026-09-09T12:00',effectiveUntil:'',active:true},7:{departments:[{id:'d',name:'Operations'}],positions:[{id:'a',departmentId:'d',title:'Valid position'},{id:'b',departmentId:'other',title:'Foreign position'}],canManage:false}});assert.match(html,/Valid position/);assert.doesNotMatch(html,/Foreign position|Pay Rate|Bill Rate|$15|$25/);assert.match(html,/New Staff Member/);});
