const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),Module=require('module'),ts=require('typescript');
for(const ext of ['.ts','.tsx'])require.extensions[ext]=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true,target:ts.ScriptTarget.ES2022}}).outputText,f);
const resolve=Module._resolveFilename;Module._resolveFilename=function(r,...a){return resolve.call(this,r.startsWith('@/')?path.resolve(__dirname,'../src',r.slice(2)):r,...a);};
const {timezoneOptions,timezoneLabel,propertyPayload}=require('../src/lib/property-form');
const {ApiError,safePropertyError}=require('../src/lib/api-error');
const React=require('react'),{renderToStaticMarkup}=require('react-dom/server');
let cursor=0,state=[],posted,failed;
const load=Module._load;Module._load=function(r,...a){
 if(r==='react')return {...React,useState(initial){const i=cursor++;if(!(i in state))state[i]=typeof initial==='function'?initial():initial;return[state[i],v=>state[i]=v];},useEffect:()=>{},useCallback:f=>f};
 if(r==='@/store/use-auth-store')return {useAuthStore:()=>({user:{role:'SUPER_ADMIN'}})};
 if(r==='@/store/use-location-store')return {useLocationStore:Object.assign(()=>({selectedLocationId:'ALL'}),{getState:()=>({fetchLocations:()=>{}})})};
 if(r==='@/lib/api-client')return {locationsApi:{create:async p=>{posted=p;if(failed)throw failed;},list:async()=>[]}};
 return load.call(this,r,...a);
};
const Page=require('../src/app/admin/(protected)/locations/page.tsx').default;
function tree(){cursor=0;return Page();}
function find(node,type){if(!node||typeof node!=='object')return; if(node.type===type)return node;for(const child of React.Children.toArray(node.props?.children)){const found=find(child,type);if(found)return found;}}
function form(){state=[];state[4]=true;state[8]={name:' Branch ',code:' CODE ',address:' Address ',timezone:'America/Merida'};failed=null;return find(tree(),'form');}
test('timezone options expose canonical identifiers and readable labels',()=>{assert.ok(timezoneOptions().includes('America/Merida'));assert.ok(!timezoneOptions().includes('Merida'));assert.match(timezoneLabel('America/Merida'),/^Mérida.*UTC/);assert.doesNotMatch(timezoneLabel('America/Merida'),/America\//);});
test('older runtime fallback and saved valid timezone remain selectable',()=>{const saved=Intl.supportedValuesOf;try{Intl.supportedValuesOf=undefined;assert.ok(timezoneOptions('Pacific/Honolulu').includes('Pacific/Honolulu'));assert.ok(timezoneOptions().includes('America/Cancun'));assert.ok(!timezoneOptions('Merida').includes('Merida'));}finally{Intl.supportedValuesOf=saved;}});
test('frontend create handler sends canonical trimmed payload without kioskCode/companyId',async()=>{await form().props.onSubmit({preventDefault(){}});assert.deepEqual(posted,{name:'Branch',code:'CODE',address:'Address',timezone:'America/Merida'});});
test('selector is required, not free text, and kiosk pairing input is absent',()=>{form();const html=renderToStaticMarkup(tree());assert.match(html,/<select[^>]*id="property-timezone"[^>]*required/);assert.match(html,/value="America\/Merida" selected/);assert.doesNotMatch(html,/Kiosk Pairing Code|Kiosk Device Code/);});
test('controlled validation reaches the rendered page error',async()=>{const f=form();failed=new ApiError(400,'A valid IANA timezone is required.');await f.props.onSubmit({preventDefault(){}});const html=renderToStaticMarkup(tree());assert.match(html,/role="alert"/);assert.match(html,/A valid IANA timezone is required/);});
test('only reviewed controlled 400/403/409 messages are displayed',()=>{for(const [code,message] of [[400,'An explicit company is required.'],[403,"Access denied: Missing required permission 'PROPERTY_MANAGE'."],[409,'Property code already exists.']])assert.equal(safePropertyError(new ApiError(code,message),'Generic'),message);});
test('internals and unexpected errors remain generic regardless of status',()=>{for(const status of [400,403,409,500])for(const message of ['PrismaClientKnownRequestError','SELECT * FROM users','Redis connection failed','at C:\\app\\service.ts:10','/app/dist/main.js','Stack trace'])assert.equal(safePropertyError(new ApiError(status,message),'Generic'),'Generic');assert.equal(safePropertyError(new ApiError(500,'A valid IANA timezone is required.'),'Generic'),'Generic');assert.equal(safePropertyError(new Error('secret'),'Generic'),'Generic');});
test('payload helper trims only edges and update need not send code',()=>{assert.deepEqual(propertyPayload({name:' A  B ',address:' C  D ',timezone:' America/Merida '}),{name:'A  B',address:'C  D',timezone:'America/Merida'});});
test('terminal configuration continues to use property identity without kioskCode',()=>{const {terminalFromProperty}=require('../src/lib/clock-context');const config=terminalFromProperty({id:'p',name:'Branch',code:'LOC-1',timezone:'America/Merida'});assert.equal(config.propertyId,'p');assert.equal(config.locationCode,'LOC-1');assert.equal(config.timezone,'America/Merida');});
test('terminology keeps employee routes and API symbols intact',()=>{const page=fs.readFileSync(path.resolve(__dirname,'../src/app/admin/(protected)/employees/page.tsx'),'utf8');assert.match(page,/Add Staff Member/);assert.match(page,/employeeNumber/);assert.match(page,/onboardingApi.create/);const api=fs.readFileSync(path.resolve(__dirname,'../src/lib/api-client.ts'),'utf8');assert.match(api,/\/onboarding\/employees/);});
test('actual API client retains HTTP status for safe display',async()=>{const original=global.fetch;const {locationsApi}=require('../src/lib/api-client');try{global.fetch=async()=>({ok:false,status:400,statusText:'Bad Request',json:async()=>({message:'A valid IANA timezone is required.'})});await assert.rejects(locationsApi.create({timezone:'Merida'}),e=>e instanceof ApiError&&e.status===400&&safePropertyError(e,'Generic')==='A valid IANA timezone is required.');}finally{global.fetch=original;}});
test('internal failure stays generic in the actual create form',async()=>{const f=form();failed=new ApiError(500,'Prisma SELECT secret FROM /app/private');await f.props.onSubmit({preventDefault(){}});const html=renderToStaticMarkup(tree());assert.match(html,/Unable to create property/);assert.doesNotMatch(html,/Prisma|SELECT|\/app\/private/);});
