const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),Module=require('module'),ts=require('typescript');
for(const ext of ['.ts','.tsx'])require.extensions[ext]=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true,target:ts.ScriptTarget.ES2022}}).outputText,f);
const resolve=Module._resolveFilename;Module._resolveFilename=function(r,...a){return resolve.call(this,r.startsWith('@/')?path.resolve(__dirname,'../src',r.slice(2)):r,...a);};
const recovery=require('../src/lib/session-recovery'),api=require('../src/lib/api-client');
function browser(){const values=new Map([['nexustaff_token','expired'],['nexustaff_user','{}'],['nexustaff-auth-store','{}'],['kiosk_terminal_config','pairing'],['unrelated','keep']]);const redirects=[];const storage={getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};return{values,redirects,window:{localStorage:storage,location:{pathname:'/admin/employees',replace:p=>redirects.push(p)}}};}
test('concurrent real API 401s clear auth once, preserve pairing and redirect once',async()=>{const b=browser(),old=global.window,fetch=global.fetch;let cleared=0;try{global.window=b.window;global.fetch=async()=>({ok:false,status:401,json:async()=>({message:'Unauthorized'})});recovery.resetSessionRecovery();recovery.registerSessionCleanup(()=>cleared++);await Promise.allSettled([api.locationsApi.list(),api.staffApi.list()]);assert.equal(cleared,1);assert.deepEqual(b.redirects,['/admin/login?session=expired']);assert.equal(b.values.get('kiosk_terminal_config'),'pairing');assert.equal(b.values.get('unrelated'),'keep');for(const key of ['nexustaff_token','nexustaff_user','nexustaff-auth-store'])assert.equal(b.values.has(key),false);}finally{global.window=old;global.fetch=fetch;}});
test('late 401 cannot clear a newer login',()=>{const b=browser(),old=global.window;try{global.window=b.window;b.values.set('nexustaff_token','new-token');recovery.resetSessionRecovery();recovery.recoverExpiredSession('expired');assert.equal(b.values.get('nexustaff_token'),'new-token');assert.equal(b.redirects.length,0);}finally{global.window=old;}});
test('public login and kiosk failures do not clear Admin auth or attach its token',async()=>{const b=browser(),old=global.window,fetch=global.fetch;let auth;try{global.window=b.window;global.fetch=async(_,options)=>{auth=options.headers.Authorization;return{ok:false,status:401,json:async()=>({message:'Invalid credentials'})};};recovery.resetSessionRecovery();await assert.rejects(api.authApi.login({email:'test@example.invalid',password:'fixture'}));assert.equal(auth,undefined);await assert.rejects(api.attendanceApi.kioskStatus({employee_number:'EMP-TEST',pin_code:'654321'}));assert.equal(auth,undefined);await assert.rejects(api.attendanceApi.kioskIdentify({pin_code:'654321',property_id:'property-test'}));assert.equal(auth,undefined);assert.equal(b.values.get('nexustaff_token'),'expired');assert.equal(b.redirects.length,0);}finally{global.window=old;global.fetch=fetch;}});
test('actual Zustand session is cleared and terminal pairing survives recovery and logout',()=>{const b=browser(),old=global.window,oldStorage=global.localStorage,fetch=global.fetch;try{global.window=b.window;global.localStorage=b.window.localStorage;global.fetch=async()=>({ok:true,status:200,json:async()=>({})});const {useAuthStore}=require('../src/store/use-auth-store');useAuthStore.setState({isAuthenticated:true,token:'expired',user:{id:'a',role:'SUPER_ADMIN'}});recovery.resetSessionRecovery();recovery.recoverExpiredSession('expired');assert.equal(useAuthStore.getState().isAuthenticated,false);assert.equal(useAuthStore.getState().token,null);assert.equal(useAuthStore.getState().user,null);assert.equal(b.values.get('kiosk_terminal_config'),'pairing');useAuthStore.getState().logout();assert.equal(b.values.get('kiosk_terminal_config'),'pairing');}finally{global.window=old;global.localStorage=oldStorage;global.fetch=fetch;}});
const {timezoneLabel,propertyPayload}=require('../src/lib/property-form');
test('Time Zone labels are readable and DST offsets follow date',()=>{const summer=timezoneLabel('America/New_York',new Date('2026-07-15T12:00:00Z')),winter=timezoneLabel('America/New_York',new Date('2026-01-15T12:00:00Z'));assert.match(summer,/New York.*UTC-4/);assert.match(winter,/New York.*UTC-5/);assert.doesNotMatch(summer,/America\//);assert.match(timezoneLabel('America/Merida'),/^Mérida/);});
test('readable presentation does not change canonical submitted value',()=>{assert.equal(propertyPayload({name:'Test',address:'Test',timezone:'America/Merida'}).timezone,'America/Merida');assert.match(timezoneLabel('Pacific/Honolulu'),/Honolulu/);});
test('intentional autocomplete semantics and focus guards distinguish identities',()=>{const read=p=>fs.readFileSync(path.resolve(__dirname,'../src',p),'utf8');const clock=read('app/clock/page.tsx'),login=read('app/admin/(auth)/login/page.tsx'),staff=read('app/admin/(protected)/employees/page.tsx');assert.doesNotMatch(clock,/name="clock-staff-number"/);assert.match(clock,/readOnly onFocus/);assert.match(clock,/name="clock-staff-pin"/);assert.match(login,/autoComplete="username"/);assert.match(login,/autoComplete="current-password"/);assert.match(staff,/section-staff email/);assert.match(staff,/section-staff new-password/);assert.match(staff,/Add Staff Member/);assert.doesNotMatch(staff,/>Employees|Create Employee/);assert.match(login,/SESSION_EXPIRED_MESSAGE/);});
