const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),Module=require('module'),ts=require('typescript');
for(const ext of ['.ts','.tsx'])require.extensions[ext]=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true,target:ts.ScriptTarget.ES2022}}).outputText,f);
const resolve=Module._resolveFilename;Module._resolveFilename=function(r,...a){return resolve.call(this,r.startsWith('@/')?path.resolve(__dirname,'../src',r.slice(2)):r,...a);};
const React=require('react');let state=[],refs=[],effects=[],cursor=0,rc=0,ec=0,queue=[],calls=[],response,scope='a';
const catalog={timezone:'America/New_York',propertyName:'North',canManage:true,departments:[{id:'d',name:'Operations'}],positions:[{id:'p',departmentId:'d',title:'Staff'}]};
const api={catalog:async id=>{calls.push(['catalog',id]);return response;},department:async()=>({id:'new-d'}),position:async()=>({id:'new-p'}),create:async data=>{calls.push(['create',data]);return{id:'u'};},add:async(id,data)=>calls.push(['add',id,data]),details:async()=>({id:'u',readiness:[],assignments:[]})};
const load=Module._load;Module._load=function(r,...a){if(r==='react')return{...React,useState(initial){const i=cursor++;if(!(i in state))state[i]=typeof initial==='function'?initial():initial;return[state[i],v=>state[i]=typeof v==='function'?v(state[i]):v];},useRef(initial){const i=rc++;return refs[i]||(refs[i]={current:initial});},useEffect(fn,deps){const i=ec++;const prior=effects[i];if(!prior||deps.some((v,j)=>v!==prior.deps[j]))queue.push(()=>{prior?.cleanup?.();effects[i]={deps,cleanup:fn()};});}};if(r==='@/store/use-auth-store')return{useAuthStore:()=>({user:{role:'SUPER_ADMIN'},token:'fixture'})};if(r==='@/store/use-location-store')return{useLocationStore:()=>({selectedLocationId:scope})};if(r==='@/lib/api-client')return{onboardingApi:api,staffApi:{list:async()=>[]},locationsApi:{list:async()=>[{id:'a',name:'North'},{id:'b',name:'South'}]}};return load.call(this,r,...a);};
const Page=require('../src/app/admin/(protected)/employees/page').default;
function tree(){cursor=rc=ec=0;return Page();}function nodes(n,p){if(!n||typeof n!=='object')return[];return[...(p(n)?[n]:[]),...React.Children.toArray(n.props?.children).flatMap(c=>nodes(c,p))];}function button(name){return nodes(tree(),n=>n.type==='button'&&n.props.children===name)[0];}function input(label){return nodes(tree(),n=>n.props?.['aria-label']===label)[0];}async function flush(){tree();const pending=queue;queue=[];pending.forEach(fn=>fn());await new Promise(r=>setImmediate(r));}async function init(){state=[];refs=[];effects=[];queue=[];calls=[];scope='a';response=catalog;await flush();await flush();}
test('reopening same Branch and Additional Assignment reloads cleared catalog',async()=>{await init();button('Add Staff Member').props.onClick();await flush();assert.equal(state[7],catalog);button('Cancel').props.onClick();await flush();button('Add Staff Member').props.onClick();await flush();assert.equal(state[7],catalog);state[2]={id:'u',readiness:[],assignments:[]};state[3]='u';button('Add Assignment').props.onClick();await flush();assert.equal(state[7],catalog);assert.ok(calls.filter(c=>c[0]==='catalog').length>=3);});
test('Branch and Department switches clear stale selections',async()=>{await init();button('Add Staff Member').props.onClick();await flush();state[5]={...state[5],departmentId:'d',positionId:'p'};input('Assignment Department').props.onChange({target:{value:'next'}});assert.equal(state[5].positionId,'');input('Assignment Branch').props.onChange({target:{value:'b'}});assert.equal(state[5].departmentId,'');assert.equal(state[5].positionId,'');assert.equal(state[7],null);});
test('empty catalog guides actor; unauthorized controls hidden; inline creations reload and select',async()=>{await init();response={...catalog,departments:[],positions:[],canManage:false};button('Add Staff Member').props.onClick();await flush();assert.equal(button('Add Department'),undefined);assert.match(require('react-dom/server').renderToStaticMarkup(tree()),/No departments are configured/);state[7]={...response,canManage:true};state[14]={name:'Ops',code:'OPS'};response={...catalog,departments:[{id:'new-d',name:'Ops'}]};await button('Add Department').props.onClick();assert.equal(state[5].departmentId,'new-d');assert.equal(state[7],response);state[15]={name:'Staff',code:'S'};response={...response,positions:[{id:'new-p',departmentId:'new-d',title:'Staff'}]};await button('Add Position').props.onClick();assert.equal(state[5].positionId,'new-p');assert.equal(state[10],'Position created.');});
test('immediate create normalizes number; future additional assignment uses same User and Branch time',async()=>{await init();button('Add Staff Member').props.onClick();await flush();state[5]={...state[5],departmentId:'d',positionId:'p'};state[6]={...state[6],employeeNumber:'010101'};const start=Date.now();await nodes(tree(),n=>n.type==='form')[0].props.onSubmit({preventDefault(){}});const data=calls.find(c=>c[0]==='create')[1];assert.equal(data.employeeNumber,'EMP-010101');assert.ok(Date.parse(data.effectiveFrom)>=start);button('Add Assignment').props.onClick();await flush();state[5]={...state[5],departmentId:'d',positionId:'p',effectiveFrom:'2099-01-01T10:00'};state[18]=false;await nodes(tree(),n=>n.type==='form')[0].props.onSubmit({preventDefault(){}});const add=calls.find(c=>c[0]==='add');assert.equal(add[1],'u');assert.equal(add[2].effectiveFrom,'2099-01-01T15:00:00.000Z');assert.equal(calls.filter(c=>c[0]==='create').length,1);});
const {assignmentState,branchDate,branchTimestamp,staffError,readinessText}=require('../src/lib/staff-ux');
test('lifecycle and Branch timezone conversion reject DST ambiguity',()=>{const now=Date.parse('2026-09-23T12:00Z');for(const [a,status] of [[{active:true,effectiveFrom:'2026-09-23T12:00Z'},'Current'],[{active:true,effectiveFrom:'2026-09-24T12:00Z'},'Scheduled'],[{active:true,effectiveFrom:'2020-01-01',effectiveUntil:'2026-09-22'},'Expired'],[{active:false,effectiveFrom:'2099-01-01'},'Inactive']])assert.equal(assignmentState(a,now),status);assert.equal(branchTimestamp('2026-09-24T14:00','America/New_York'),'2026-09-24T18:00:00.000Z');for(const value of ['2026-03-08T02:30','2026-11-01T01:30'])assert.throws(()=>branchTimestamp(value,'America/New_York'),/daylight/);assert.match(branchDate('2026-09-24T18:00Z','America/New_York'),/2:00 PM/);});
test('safe errors hide internals and readiness explanations preserve server authority',()=>{for(const message of ['employeeNumber must match /^EMP-/ regular expression','Prisma P2002 user 123','Error stack trace'])assert.doesNotMatch(staffError({message}),/Prisma|P2002|employeeNumber|regular expression|stack/);assert.match(readinessText({clockReady:false,name:'North',reason:'ASSIGNMENT_SCHEDULED',effectiveFrom:'2026-09-24T18:00Z',timezone:'America/New_York'}),/2:00 PM/);for(const reason of ['STAFF_INACTIVE','PIN_MISSING','ASSIGNMENT_EXPIRED','ASSIGNMENT_INACTIVE','ASSIGNMENT_MISSING','ASSIGNMENT_UNAVAILABLE'])assert.ok(readinessText({clockReady:false,name:'North',reason}).length>20);});
test('late catalog response from old Branch never overwrites current Branch',async()=>{await init();button('Add Staff Member').props.onClick();await flush();let finish;const original=api.catalog;api.catalog=()=>new Promise(r=>finish=r);input('Assignment Branch').props.onChange({target:{value:'b'}});await flush();input('Assignment Branch').props.onChange({target:{value:'a'}});api.catalog=original;await flush();finish({...catalog,propertyName:'Foreign'});await new Promise(r=>setImmediate(r));assert.equal(state[7],catalog);});
test('duplicate inline submit is blocked while first catalog mutation is pending',async()=>{await init();button('Add Staff Member').props.onClick();await flush();state[14]={name:'Ops',code:'OPS'};const original=api.department;let finish,count=0;api.department=()=>{count++;return new Promise(r=>finish=r);};try{const handler=button('Add Department').props.onClick;const first=handler();await handler();assert.equal(count,1);finish({id:'d'});await first;}finally{api.department=original;}});
