const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),Module=require('module'),ts=require('typescript');
for(const ext of ['.ts','.tsx'])require.extensions[ext]=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true,target:ts.ScriptTarget.ES2022}}).outputText,f);
const resolve=Module._resolveFilename;Module._resolveFilename=function(r,...a){return resolve.call(this,r.startsWith('@/')?path.resolve(__dirname,'../src',r.slice(2)):r,...a);};const React=require('react');
let refs=[],rc=0,state=[],cursor=0,calls=[],user,changes=0;
const api={list:async()=>[],create:async d=>calls.push(d),review:async(...a)=>calls.push(a)};
const load=Module._load;Module._load=function(r,...a){if(r==='react')return {...React,useState(initial){const i=cursor++;if(!(i in state))state[i]=initial;return[state[i],v=>state[i]=typeof v==='function'?v(state[i]):v];},useRef(initial){const i=rc++;return refs[i]||(refs[i]={current:initial});},useEffect:()=>{}};if(r==='@/store/use-auth-store')return{useAuthStore:()=>({user})};if(r==='@/lib/api-client')return{timeCorrectionsApi:api};return load.call(this,r,...a);};
const {TimeCorrections}=require('../src/components/reports/time-corrections');
function tree(){cursor=rc=0;return TimeCorrections({locationId:'a',branch:{name:'Florida Beach',timezone:'America/New_York'},rows:[{staff:{firstName:'Staff'},shifts:[{id:'s',clockIn:'2026-01-05T12:00:00Z',status:'MISSED_CLOCK_OUT'}]}],onChanged:async()=>changes++});}
function nodes(n,p){if(!n||typeof n!=='object')return[];return[...(p(n)?[n]:[]),...React.Children.toArray(n.props?.children).flatMap(c=>nodes(c,p))];}
function init(){state=[];refs=[];calls=[];changes=0;user={role:'OWNER',companyId:'c'};tree();}
test('actual correction form sends selected canonical shift and converted timestamp, then clears temporary input',async()=>{init();state[1]='s';state[3]='2026-01-05T18:00';state[4]='Verified exit';nodes(tree(),n=>n.type==='form')[0].props.onSubmit({preventDefault(){}});await new Promise(r=>setImmediate(r));assert.deepEqual(calls,[{location_id:'a',work_shift_id:'s',correction_type:'MISSED_CLOCK_OUT',requested_timestamp:new Date('2026-01-05T18:00').toISOString(),reason:'Verified exit'}]);assert.equal(state[3],'');assert.equal(state[4],'');assert.equal(changes,1);});
test('missing correction capability hides form; rejection requires reviewer comments',()=>{init();user={role:'SUPERVISOR',companyId:'c',assignedLocationIds:['a'],permissions:['TIME_VIEW','TIME_APPROVE']};state[0]=[{id:'c',status:'PENDING'}];assert.equal(nodes(tree(),n=>n.type==='form').length,0);const reject=nodes(tree(),n=>n.type==='button'&&n.props.children==='Reject correction')[0];assert.equal(reject.props.disabled,false);reject.props.onClick({currentTarget:{focus(){}}});const confirm=nodes(tree(),n=>n.type==='button'&&n.props.children==='Reject correction').at(-1);assert.equal(confirm.props.disabled,true);});
function pendingRequest(){init();state[0]=[{id:'c',workShiftId:'s',status:'PENDING',correctionType:'INCORRECT_CLOCK_IN',requestedTimestamp:'2026-09-24T01:30:00Z',reason:'Verified with supervisor',user:{firstName:'Test',lastName:'Staff'}}];}
const clickEvent={currentTarget:{focus(){}}};
const buttons=name=>nodes(tree(),n=>n.type==='button'&&n.props.children===name);
const settle=()=>new Promise(r=>setImmediate(r));
test('Approve opens confirmation; Cancel and Escape cause no mutation; controls are distinct',()=>{pendingRequest();const approve=buttons('Approve correction')[0],reject=buttons('Reject correction')[0];assert.notEqual(approve.props.className,reject.props.className);approve.props.onClick(clickEvent);assert.equal(calls.length,0);assert.equal(buttons('Cancel').length,1);buttons('Cancel')[0].props.onClick();assert.equal(state[9],null);assert.equal(calls.length,0);reject.props.onClick(clickEvent);nodes(tree(),n=>n.type==='dialog')[0].props.onCancel({preventDefault(){}});assert.equal(state[9],null);assert.equal(calls.length,0);});
test('confirmation sends exactly one request despite duplicate clicks; loading state protects dismissal',async()=>{pendingRequest();const old=api.review;let finish;api.review=(...args)=>{calls.push(args);return new Promise(r=>finish=r);};try{buttons('Approve correction')[0].props.onClick(clickEvent);const confirm=buttons('Approve correction').at(-1);confirm.props.onClick();confirm.props.onClick();assert.equal(calls.length,1);assert.equal(buttons('Cancel')[0].props.disabled,true);buttons('Cancel')[0].props.onClick();assert.ok(state[9]);finish();await settle();assert.equal(state[7],'Correction approved.');}finally{api.review=old;}});
test('Reject requires confirmation and comments, then sends existing rejection API',async()=>{pendingRequest();buttons('Reject correction')[0].props.onClick(clickEvent);assert.equal(calls.length,0);assert.equal(buttons('Reject correction').at(-1).props.disabled,true);state[5]='Incorrect proposed time';buttons('Reject correction').at(-1).props.onClick();await settle();assert.deepEqual(calls,[['c','reject','Incorrect proposed time']]);assert.equal(state[7],'Correction rejected.');});
test('invalid approval stays Pending after authoritative reload; safe persistent error and Reject remain',async()=>{pendingRequest();const old=api.review,oldList=api.list,record=state[0][0];api.review=async()=>{throw Object.assign(Error('Invalid correction range: Effective CLOCK_OUT must be after effective CLOCK_IN.'),{status:400});};api.list=async()=>[record];try{buttons('Approve correction')[0].props.onClick(clickEvent);buttons('Approve correction').at(-1).props.onClick();await settle();assert.equal(state[0][0].status,'PENDING');assert.match(state[6],/remains Pending/);assert.match(state[6],/Clock In.*Clock Out/);assert.doesNotMatch(state[6],/CLOCK_IN|CLOCK_OUT|Prisma/);assert.equal(buttons('Reject correction').length,1);}finally{api.review=old;api.list=oldList;}});
test('Approved immutable explanation and existing subsequent-correction flow; Branch time is primary',()=>{pendingRequest();state[0][0].status='APPROVED';const html=require('react-dom/server').renderToStaticMarkup(tree());assert.match(html,/cannot be edited directly/);assert.match(html,/Sep 23, 2026, 9:30 PM/);assert.match(html,/Florida Beach time/);assert.equal(buttons('Approve correction').length,0);assert.equal(buttons('Reject correction').length,0);assert.equal(nodes(tree(),n=>n.type==='time')[0].props.children,'Sep 23, 2026, 9:30 PM');buttons('Create another correction')[0].props.onClick();assert.equal(state[1],'s');assert.equal(state[2],'INCORRECT_CLOCK_IN');assert.equal(state[0][0].status,'APPROVED');});
test('unknown internal errors are never exposed and range guidance follows correction direction',()=>{const {correctionError}=require('../src/lib/correction-ux');assert.doesNotMatch(correctionError({message:'Prisma P2002 stack trace'},'MISSED_CLOCK_OUT'),/Prisma|P2002|stack/);assert.match(correctionError({message:'Effective CLOCK_OUT must be after effective CLOCK_IN'},'INCORRECT_CLOCK_OUT'),/Choose a later Clock Out/);});
test('successful review followed by refresh failure reports saved, never failed or Pending',async()=>{pendingRequest();const old=api.list;api.list=async()=>{throw Error('offline');};try{buttons('Approve correction')[0].props.onClick(clickEvent);buttons('Approve correction').at(-1).props.onClick();await settle();assert.equal(state[0][0].status,'APPROVED');assert.equal(state[7],'Correction approved.');assert.match(state[6],/was saved/);assert.equal(buttons('Approve correction').length,0);}finally{api.list=old;}});
test('uncertain network failure plus unavailable refresh never claims request is still Pending',async()=>{pendingRequest();const old=api.list,oldReview=api.review;api.list=async()=>{throw Error('offline');};api.review=async()=>{throw Error('network interrupted');};try{buttons('Approve correction')[0].props.onClick(clickEvent);buttons('Approve correction').at(-1).props.onClick();await settle();assert.match(state[6],/may have completed/);assert.doesNotMatch(state[6],/remains Pending/);}finally{api.list=old;api.review=oldReview;}});
