const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),Module=require('module'),ts=require('typescript');
for(const ext of ['.ts','.tsx'])require.extensions[ext]=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true,target:ts.ScriptTarget.ES2022}}).outputText,f);
const resolve=Module._resolveFilename;Module._resolveFilename=function(r,...a){return resolve.call(this,r.startsWith('@/')?path.resolve(__dirname,'../src',r.slice(2)):r,...a);};const React=require('react');
let state=[],cursor=0,calls=[],user,changes=0;
const api={list:async()=>[],create:async d=>calls.push(d),review:async(...a)=>calls.push(a)};
const load=Module._load;Module._load=function(r,...a){if(r==='react')return {...React,useState(initial){const i=cursor++;if(!(i in state))state[i]=initial;return[state[i],v=>state[i]=v];},useEffect:()=>{}};if(r==='@/store/use-auth-store')return{useAuthStore:()=>({user})};if(r==='@/lib/api-client')return{timeCorrectionsApi:api};return load.call(this,r,...a);};
const {TimeCorrections}=require('../src/components/reports/time-corrections');
function tree(){cursor=0;return TimeCorrections({locationId:'a',rows:[{staff:{firstName:'Staff'},shifts:[{id:'s',clockIn:'2026-01-05T12:00:00Z',status:'MISSED_CLOCK_OUT'}]}],onChanged:async()=>changes++});}
function nodes(n,p){if(!n||typeof n!=='object')return[];return[...(p(n)?[n]:[]),...React.Children.toArray(n.props?.children).flatMap(c=>nodes(c,p))];}
function init(){state=[];calls=[];changes=0;user={role:'OWNER',companyId:'c'};tree();}
test('actual correction form sends selected canonical shift and converted timestamp, then clears temporary input',async()=>{init();state[1]='s';state[3]='2026-01-05T18:00';state[4]='Verified exit';nodes(tree(),n=>n.type==='form')[0].props.onSubmit({preventDefault(){}});await new Promise(r=>setImmediate(r));assert.deepEqual(calls,[{location_id:'a',work_shift_id:'s',correction_type:'MISSED_CLOCK_OUT',requested_timestamp:new Date('2026-01-05T18:00').toISOString(),reason:'Verified exit'}]);assert.equal(state[3],'');assert.equal(state[4],'');assert.equal(changes,1);});
test('missing correction capability hides form; rejection requires reviewer comments',()=>{init();user={role:'SUPERVISOR',companyId:'c',assignedLocationIds:['a'],permissions:['TIME_VIEW','TIME_APPROVE']};state[0]=[{id:'c',status:'PENDING'}];assert.equal(nodes(tree(),n=>n.type==='form').length,0);const reject=nodes(tree(),n=>n.type==='button'&&n.props.children==='Reject correction')[0];assert.equal(reject.props.disabled,true);});
